#!/usr/bin/env bash
# vim: fdl=0

mg() { # @@ # {{{
  if [[ $1 == @@ ]]; then
    echo "+g +ack +ag +rg +tee=true +tee=false +-fzf +fzf"
    return 0
  fi
  local cmd="ag"
  ! which $cmd >/dev/null 2>&1 && cmd="rg"
  ! which $cmd >/dev/null 2>&1 && cmd="ack"
  ! which $cmd >/dev/null 2>&1 && cmd="grep"
  local tee=true use_fzf= fzf_params=
  local defaultGrepCmd=${MG_DEFAULT_GREP:-pgrep}
  ! which $defaultGrepCmd >/dev/null 2>&1 && defaultGrepCmd="grep"
  while [[ ! -z $1 ]]; do
    case $1 in
    +g)     cmd="grep";;
    +ack)   cmd="ack";;
    +ag)    cmd="ag";;
    +rg)    cmd="rg";;
    +tee=*) tee="${1/+tee=}";;
    +-fzf | +-f) use_fzf=false;;
    +fzf  | +f)  use_fzf=$FZF_INSTALLED;;
    +fzf=*)      use_fzf=${1/+fzf=}; $use_fzf && use_fzf=$FZF_INSTALLED;;
    +fzf-*)      fzf_params+=" $1";;
    *)      break;;
    esac
    shift
  done
  if [[ -z $use_fzf ]]; then # {{{
    if [[ ! -t 1 ]]; then
      use_fzf=false
    else
      eval $FZF_USAGE
      use_fzf=${fzfUsageA[mg]:-$FZF_INSTALLED}
    fi
  fi # }}}
  local err=
  case $cmd in
  grep*) $ENV_SCRIPTS/grep-tools/grep-wrapper.sh   --cmd-$defaultGrepCmd +tee=$tee +fzf=$use_fzf $fzf_params -R "$@" *;;
  ack*)  $ENV_SCRIPTS/grep-tools/ack-ag-wrapper.sh --cmd-ack +tee=$tee +fzf=$use_fzf $fzf_params "$@";;
  ag*)   $ENV_SCRIPTS/grep-tools/ack-ag-wrapper.sh --cmd-ag  +tee=$tee +fzf=$use_fzf $fzf_params "$@";;
  rg*)   $ENV_SCRIPTS/grep-tools/ack-ag-wrapper.sh --cmd-rg  +tee=$tee +fzf=$use_fzf $fzf_params "$@";;
  esac
} # }}}
gr() { # @@ # {{{
  if [[ $1 == '@@' ]]; then
    echo +c={Gray,Red,Green,Yellow,Blue,Pink,Cyan,Gold,Hls,Search}
    echo "+i"
    return 0
  fi
  local params="--line-buffered"
  [[ $1 == '+i' ]] && params+=" +i" && shift
  [[ -t 1 ]] && params+=" --colors"
  $ENV_SCRIPTS/grep-tools/grep-wrapper.sh --cmd-pgrep +tee=false $params "$@"
} # }}}

