#!/usr/bin/env bash
# vim: fdl=0

mg() { # @@:new # {{{
  if [[ $1 == "@@" ]]; then # {{{
    echo "+g"
    return 0
  fi # }}}
  local cmd="rg" params="-S"
  is-installed -w $cmd || cmd="ag"
  while [[ -n $1 ]]; do # {{{
    case $1 in
    +g)
      cmd="grep"; params="-rP"
      shift
      set -- "$@" .
      break;;
    *) break;;
    esac; shift
  done # }}}
  out() { # {{{
    fzf --prompt "mg> " -m --sort --ansi
  } # }}}
  if [[ -t 1 ]]; then # {{{
    case $cmd in
    ag) params+=" --color";;
    *)  params+=" --color=always";;
    esac
  else
    out() { cat -; }
  fi # }}}
  $cmd $params "$@" | out
  return 0
} # }}}
gr() { # @@:new # {{{
  if [[ $1 == "@@" ]]; then # {{{
    echo "+g"
    return 0
  fi # }}}
  local cmd="rg" params="-S"
  is-installed -w $cmd || cmd="ag"
  is-installed -w $cmd || { cmd="grep"; params="-iP"; }
  while [[ -n $1 ]]; do # {{{
    case $1 in
    +g)
      cmd="grep"; params="-P"
      shift; break;;
    *) break;;
    esac; shift
  done # }}}
  $cmd $params "$@"
} # }}}
