#!/usr/bin/env bash
# vim: fdl=0

__ps1_load_defaults() { # {{{
  unset PS1_CONVERTER_ADD_SEPARATOR PS1_CONVERTER_ENV_VENV PS1_CONVERTER_NEW_LINE
  PS1_CFG_LINES=${PS1_CFG_LINES:-12}
  PS1_CFG_LINES_FOR_SPLIT=${PS1_CFG_LINES_FOR_SPLIT:-8}
  PS1_CFG_WIDTH=${PS1_CFG_WIDTH:-45}
  PS1_CFG_SEPARATOR=${PS1_CFG_SEPARATOR:-${UNICODE_EXTRA_CHARS[sep-x]}}
  PS1_CFG_HIST=${PS1_CFG_HIST:-${UNICODE_EXTRA_CHARS[pause]}}
  PS1_COLUMNS_MARGIN=${PS1_COLUMNS_MARGIN:-40}
  PS1_COLOR_OFF="${PS1_COLOR_OFF:-$(echo "\[$COff\]")}"
  PS1_COLOR_ERR_0="${PS1_COLOR_ERR_0:-$(echo "\[$CIYellow\]")}"
  PS1_COLOR_ERR_ERR="${PS1_COLOR_ERR_ERR:-$(echo "\[$CIRed\]")}"
  PS1_COLOR_HIST_LOCAL="${PS1_COLOR_HIST_LOCAL:-$(echo "\[$CIBlue\]")}"
  PS1_COLOR_HIST_NO="${PS1_COLOR_HIST_NO:-$(echo "\[$CIPurple\]")}"
  PS1_COLOR_TIME="${PS1_COLOR_TIME:-$(echo "\[$CGray\]")}"
  PS1_COLOR_USER="${PS1_COLOR_USER:-$(echo "\[$CGray\]")}"
  PS1_COLOR_HOST="${PS1_COLOR_HOST:-$(echo "\[$CGold\]")}"
  PS1_COLOR_PWD="${PS1_COLOR_PWD:-$(echo "\[$CBlue\]")}"
  PS1_COLOR_GIT="${PS1_COLOR_GIT:-$(echo "\[$CGray\]")}"
  PS1_COLOR_JOBS="${PS1_COLOR_JOBS:-$(echo "\[$CIRed\]")}"
  PS1_COLOR_JOBS_R="${PS1_COLOR_JOBS_R:-$(echo "\[$CIGreen\]")}"
  PS1_COLOR_JOBS_S="${PS1_COLOR_JOBS_S:-$(echo "\[$CGold\]")}"
  PS1_COLOR_NL="${PS1_COLOR_NL:-$(echo "\[$CGray\]")}"
  PS1_CURSOR= PS1_CURSOR_ROOT=
  if ${PS1_CURSORS_CUSTOM:-true}; then
    if [[ $PS1_CURSOR_COLOR != 'false' ]]; then
      PS1_CURSOR+="$(echo "\[\e]12;${PS1_CURSOR_COLOR:-#00afaf}\a\]")" # Set color to blue (#005e5d)
    fi
    if [[ $PS1_CURSOR_TYPE != 'false' ]]; then
      PS1_CURSOR+="$(echo "\[\e[${PS1_CURSOR_TYPE:-2} q\]")" # Type(steady,blinking): block(1,2), underline(3,4), bar(5,6)
    fi
    if [[ $PS1_CURSOR_ROOT_COLOR != 'false' ]]; then
      PS1_CURSOR_ROOT+="$(echo "\[\e]12;${PS1_CURSOR_ROOT_COLOR:-#ff5f00}\a\]")" # Set color to blue (#005e5d)
    fi
    if [[ $PS1_CURSOR_ROOT_TYPE != 'false' ]]; then
      PS1_CURSOR_ROOT+="$(echo "\[\e[${PS1_CURSOR_ROOT_TYPE:-1} q\]")" # Type(steady,blinking): block(1,2), underline(3,4), bar(5,6)
    fi
  fi
} # }}}
PS1_getColor() { # {{{
  case $1 in
  err-*)    case ${1#err-} in
            0 | 141) echo -en "$PS1_COLOR_ERR_0";; # hide sigpipe, e.g. git log
            *)       echo -en "$PS1_COLOR_ERR_ERR";;
            esac;;
  hist)     if [[ ! -z $BASH_PHISTORY_FILE && ! -z $HISTFILE && ( $HISTFILE == $HISTFILE_ORIG || $HISTFILE =~ .*/\.history(\.ign)?$ ) ]]; then
              :
            elif [[ ! -z $HISTFILE && $HISTFILE != $HISTFILE_ORIG && $HISTFILE =~ .*/\.history(\.ign)?$ ]] || ${TMUX_POPUP:-false}; then
              echo -en "$PS1_COLOR_HIST_LOCAL"
            else
              echo -en "$PS1_COLOR_HIST_NO"
            fi;;
  user)     echo -en "$PS1_COLOR_USER";;
  host)     echo -en "$PS1_COLOR_HOST";;
  pwd)      echo -en "$PS1_COLOR_PWD";;
  git)      echo -en "$PS1_COLOR_GIT";;
  off)      echo -en "$PS1_COLOR_OFF";;
  jobs)     echo -en "$PS1_COLOR_JOBS";;
  j-r)      echo -en "$PS1_COLOR_JOBS_R";;
  j-s)      echo -en "$PS1_COLOR_JOBS_S";;
  new-line) echo -en "$PS1_COLOR_NL";;
  cursor)   if [[ $UID != 0 ]]; then
              echo -en "$PS1_CURSOR"
            else
              echo -en "$PS1_CURSOR_ROOT"
            fi;;
  time)     echo -en "$PS1_COLOR_TIME";;
  *)        printf "%s" $(get-color $1);;
  esac
} # }}}
PS1_getPwdMode() { # {{{
  local pwdMode="pwd-short"
  case $1 in
  *_full)   pwdMode="pwd";;
  default*) pwdMode="pwd-tmux";;
  esac
  echo "$pwdMode"
} # }}}
PS1_covertMode() { # {{{
  local mode=
  case $1 in
  usuper_full)   mode=' env-switches user host pwd jobs git';;
  super_full)    mode=' env-switches      host pwd jobs git';;
  default_ussh)  mode=' env-switches user host pwd jobs git';;
  default_ssh)   mode=' env-switches      host pwd jobs git';;
  default)       mode=' env-switches           pwd jobs git';;
  short)         mode='                        pwd jobs';;
  short_git_ssh) mode=' env-switches      host pwd jobs git';;
  short_git)     mode=' env-switches           pwd jobs git';;
  very_short)    mode='';;
  esac
  [[ "$PS1_ENV_MODE" != 'false' ]] && mode+=" env"
  mode+=' split-line'
  mode+=' hist'
  mode+=' prompt'
  [[ $TERM_ORIG != 'linux' ]] && mode+=' cursor'
  [[ ! -z $EPOCHREALTIME ]] && mode+=" time"
  echo "$mode"
} # }}}
PS1_adjustPath() { # {{{
  local p="$1"
  [[ $p == $HOME* ]] && p=${p/#$HOME/\~}
  ! ${PS1_CFG_SHORTEN_PATH:-true} && printf "$p" && return 0
  local tmp=${p%/*}
  local last=${p/$tmp\/}
  local res=
  [[ $p == /* ]] && res="/"
  if [[ $tmp != $p ]]; then
    local i=
    for i in ${tmp//\// }; do
      if [[ $i == '...' ]]; then
        res+="$i"
      else
        res+="${i:0:1}"
      fi
      res+="/"
    done
  fi
  res+="$last"
  printf "$res"
  return 0
} # }}}
PS1_colorFormat() { # {{{
  local updateDummy=true
  local -n var=$1; shift
  [[ $1 == '-' ]] && shift && updateDummy=false
  [[ ! -z $2 ]] && var+="$(PS1_getColor "$1")$2$cOff$3"
  $updateDummy && ps1_dummy+="$2$3"
} # }}}
PS1_setter() { # {{{
  local cTime=${EPOCHREALTIME/[,.]}
  if [[ -e "$PWD" ]] && ${PS1_CONVERTER_CHECK_INODE:-true}; then # {{{
    local ino="$(command ls -id "$PWD" 2>/dev/null)"
    if [[ "$PWD" == "$PS1_LAST_PWD" ]]; then
      if [[ -z "$ino" || "$ino" != "$PS1_LAST_PWD_INO" ]]; then
        local oPWD=$OLDPWD
        command cd "$PWD"
        OLDPWD="$oPWD"
        PS1_LAST_PWD_INO="$(command ls -id "$PWD" 2>/dev/null)"
        echoe -f "Directory has changed"
      fi
    else
      PS1_LAST_PWD="$PWD"
      PS1_LAST_PWD_INO="$ino"
    fi
  else
    unset PS1_LAST_PWD PS1_LAST_PWD_INO
  fi # }}}
  PS1=""
  local spaceForTime=false
  if [[ $LINES -ge $PS1_CFG_LINES ]]; then # {{{
    ${PS1_CONVERTER_ADD_SEPARATOR:-false} && [[ $PS0_time != 0 ]] && PS1="\n"
    spaceForTime=true
  fi # }}}
  if [[ $PS0_time == 0 ]]; then # {{{
    PS1_LAST_EMPTY_STRIKE=$((PS1_LAST_EMPTY_STRIKE + 1))
    if [[ ! -z $PS1_LAST_EMPTY && $PS1_CFG_CLR_TIMEOUT != 0 ]]; then
      [[ $((cTime - PS1_LAST_EMPTY)) -lt ${PS1_CFG_CLR_TIMEOUT:-750000} ]] && clr
    fi
    [[ $__save_BASH_LAST_ERR == 0 || $PS1_LAST_EMPTY_STRIKE -ge 1 ]] && PS1_LAST_EMPTY=${EPOCHREALTIME/[,.]}
    __save_BASH_LAST_ERR=0
    PS0_time=
  else
    PS1_LAST_EMPTY_STRIKE=0
  fi # }}}
  [[ -z $PS1_COLOR_OFF ]] && __ps1_load_defaults
  [[ -z $PS1_CONVERTER_ADD_SEPARATOR ]] && PS1_CONVERTER_ADD_SEPARATOR=${PS1_CFG_ADD_SEPARATOR:-true}
  local cOff="$(PS1_getColor 'off')"
  local v= ps1_dummy=
  if [[ -z $PS1_STATUS ]]; then
    export PS1_STATUS="short_git:default"
    [[ -n "$SSH_CLIENT" && ! -n $TMUX ]] && export PS1_STATUS="short_git_ssh:default_ssh"
  fi
  local pwdMode="$(PS1_getPwdMode "${PS1_STATUS/:*}")"
  ! $spaceForTime && [[ $pwdMode == 'pwd-short' && $COLUMNS -gt 90 ]] && spaceForTime=true
  local modes="time env env-switches user host pwd git jobs split-line hist prompt cursor"
  local modesCurrent="$(PS1_covertMode "${PS1_STATUS/:*}")"
  for v in $modes; do
    [[ " $modesCurrent " == *" $v "* ]] || { continue; }
    ${PS1_PROFILER:-false} && local tt=${EPOCHREALTIME/[,.]}
    while true; do case $v in
    time) # {{{
      local timeV=
      if ${PS1_CFG_ADD_TIME_START:-false} && [[ ! -z $PS0_time ]]; then # {{{
        timeV+="$(command date +"$TIME_FMT" -d @${PS0_time%??????})"
      fi # }}}
      if ${PS1_CFG_ADD_TIME_DELTA:-false} && [[ ! -z $PS0_time ]]; then # {{{
        local diff=$(($cTime - $PS0_time))
        diff=${diff%???}
        local ms=$((diff % 1000))
        local s=$(( (diff - ms)/1000))
        [[ ! -z $timeV ]] && timeV+="$PS1_CFG_SEPARATOR"
        timeV+="$s.$(printf "%03d" "$ms")"
      fi # }}}
      if ${PS1_CFG_ADD_TIME_CURRENT:-false} || ( $spaceForTime && [[ -z $PS1_CFG_ADD_TIME_CURRENT ]] ); then # {{{
        [[ ! -z $timeV ]] && timeV+="$PS1_CFG_SEPARATOR"
        timeV+="\t"
      fi # }}}
      [[ ! -z $timeV ]] && PS1_colorFormat PS1 'time' "$timeV ";; # }}}
    env) # {{{
      local envRecursive=false
      [[ $PS1_ENV_MODE == "env" ]] && envRecursive=true
      local vv=${PS1_ENV_MODE:-env-no-rec}
      if [[ -e "$PWD" && "$PS1_ENV_PWD" != "$PWD" ]]; then
        cd_go_up() { # {{{
          local p="$1"
          [[ -z $p || ! -d $p ]] && return 0
          [[ $p != "$PS1_ENV_PWD" && $p == $HOME/* ]] && $envRecursive && cd_go_up "${p%/*}"
          [[ -e "$p/.env-setup.sh" ]] && source "$p/.env-setup.sh"
          [[ -e "$p/.env" ]] && source "$p/.env"
        } # }}}
        cd_go_up "$PWD"
        unset cd_go_up
        if [[ ${PS1_HIST_CHANGE_TO_LOCAL:-true} && ! ${TMUX_POPUP:-false} && $HISTFILE == $HISTFILE_ORIG && ( -e $PWD/.history || -e $PWD/.history.ign ) ]]; then # {{{
          [[ -z $BASH_ORIG_HISTFILE ]] && export BASH_ORIG_HISTFILE="$HISTFILE"
          export HISTFILE="$PWD/.history"
          [[ -e $PWD/.history.ign && ! -e $PWD/.history ]] && export HISTFILE="$PWD/.history.ign"
        fi # }}}
        export PS1_ENV_PWD="$PWD"
      fi;; # }}}
    env-switches) # {{{
      if [[ ! -z $VIRTUAL_ENV ]]; then
        [[ -z $PS1_CONVERTER_ENV_VENV ]] && PS1_CONVERTER_ENV_VENV="${UNICODE_EXTRA_CHARS[snake]}"
        PS1+="$PS1_CONVERTER_ENV_VENV "; ps1_dummy+=".."
      fi;; # }}}
    user) # {{{
      PS1_colorFormat PS1 'user' "$USER" "@";; # }}}
    host) # {{{
      if [[ ! -z $PS1_CACHE_HOST_V ]];then # {{{
        PS1+="$PS1_CACHE_HOST_V"; ps1_dummy+="$PS1_CACHE_HOST_D"
        break
      fi # }}}
      local name=${PS1_HOSTNAME:-${HOSTNAME^^}} p=
      for p in $TMUX_REMOTE_PREFIXES; do
        name="${name/$p}"
      done
      PS1_CACHE_HOST_D="${name^^}|"; PS1_CACHE_HOST_V=
      PS1_colorFormat PS1_CACHE_HOST_V 'host' "$name" "|"
      PS1+="$PS1_CACHE_HOST_V";; # }}}
    pwd) # {{{
      if [[ ! -e $PWD ]]; then # {{{
        if [[ $PWD == $PS1_CACHE_PWD ]]; then
          PS1+="$PS1_CACHE_PWD_V"; ps1_dummy+="$PS1_CACHE_PWD_D"
        else
          PS1+="${PWD##*/}"; ps1_dummy+="${PWD##*/}"
        fi
        PS1+="${UNICODE_EXTRA_CHARS[exclamation]}"; ps1_dummy+="."
        PS1_colorFormat PS1 err "ne"
        break
      fi # }}}
      if [[ $PWD == $PS1_CACHE_PWD ]]; then # {{{
        PS1+="$PS1_CACHE_PWD_V"; ps1_dummy+="$PS1_CACHE_PWD_D"
        break
      fi # }}}
      case $pwdMode in
      pwd) # {{{
        PS1_CACHE_PWD="$PWD"
        local p=
        case $PWD in
        $HOME) p='~';;
        /)     p='/';;
        *)
          p=$(echo "${PWD/$HOME/\~}");
          local pp=${p%/*} pr=${p##*/}
          p="$(echo "$pp" | sed -E 's|/([^/]{3})[^/]*|/\1|g')/$pr";;
        esac;; # }}}
      pwd-tmux) # {{{
        PS1_CACHE_PWD="$PWD"
        local p=
        if [[ -n $TMUX ]]; then
          case $PWD in
          $HOME) p='~';;
          /)     p='/';;
          *)
            local tmp="$PWD"
            local ps1_ignored=$PS1_IGNORED
            if [[ -z $ps1_ignored ]]; then
              ps1_ignored="$(tmux show-options -v @tmux_path 2>/dev/null)"
              [[ $ps1_ignored == $HOME || $ps1_ignored == '/' ]] && ps1_ignored=
            fi
            if [[ ! -z $ps1_ignored && $tmp == $ps1_ignored* ]]; then
              tmp=".../${tmp/#$ps1_ignored/${ps1_ignored/*\/}}"
              [[ $ps1_ignored == $HOME* ]] && tmp="~/$tmp"
            fi
            p="$(PS1_adjustPath "$tmp")";;
          esac
        else
          p=$(PS1_adjustPath "$PWD")
        fi;; # }}}
      pwd-short) # {{{
        PS1_CACHE_PWD="$PWD"
        local p=
        case $PWD in
        $HOME) p='~';;
        /)     p='/';;
        *)     p="${PWD##*/}";;
        esac;; # }}}
      esac
      PS1_CACHE_PWD_D="$p"; PS1_CACHE_PWD_V=
      PS1_colorFormat PS1_CACHE_PWD_V 'pwd' "$p"
      PS1+="$PS1_CACHE_PWD_V";; # }}}
    git) # {{{
      [[ -e $PWD ]] || break
      if [[ -z $PS1_CFG_ADD_GIT ]]; then
        ${TMUX_STATUS_RIGHT_GIT_STATUS:-true} && [[ -n $TMUX ]] && break
      else
        $PS1_CFG_ADD_GIT || break
      fi
      local l= statF=$MEM_KEEP/tmux-git
      if ${PS1_CFG_GIT_USE_CACHE:-false} && [[ -e $statF ]]; then
        l=$(source "$statF"; echo "${git_stat[$PWD]}")
      else
        l="$(unset GIT_PS1_SHOWCOLORHINTS; __git_ps1 "%s")"
      fi
      [[ -z $l ]] && break
      l="${l/<>/${UNICODE_EXTRA_CHARS[exclamation]}}"
      PS1_colorFormat PS1 'git' "${UNICODE_EXTRA_CHARS[bracket-open]}$l${UNICODE_EXTRA_CHARS[bracket-close]}";; # }}}
    jobs) # {{{
      [[ -e $PWD ]] || break
      ${PS1_CFG_ADD_JOBS:-true} || break
      if [[ ! -z $(jobs -p) ]]; then
        sleep 0.05
        local jobs_r=$(jobs -rp) jobs_s=$(jobs -sp) cnt= # _r: running, _s: suspended
        if [[ ! -z $jobs_r || ! -z $jobs_s ]]; then
          PS1_colorFormat PS1 'jobs' "${UNICODE_EXTRA_CHARS[bracket-open]}"
          if [[ ! -z $jobs_r ]]; then
            cnt="$(echo -e "$jobs_r" | wc -l | xargs)"
            PS1_colorFormat PS1 'j-r' "$cnt"
          fi
          if [[ ! -z $jobs_s ]]; then
            cnt="$(echo -e "$jobs_s" | wc -l | xargs)"
            [[ ! -z $jobs_r ]] && PS1_colorFormat PS1 'jobs' ":"
            PS1_colorFormat PS1 'j-s' "$cnt"
          fi
          PS1_colorFormat PS1 'jobs' "${UNICODE_EXTRA_CHARS[bracket-close]}"
        fi
      fi;; # }}}
    split-line) # {{{
      [[ ${#ps1_dummy} -ge 4 ]] || break
      if ( ( ${PS1_CFG_ADD_SPLIT:-true} && [[ $LINES -ge $PS1_CFG_LINES_FOR_SPLIT ]] ) || [[ ${#ps1_dummy} -gt $PS1_CFG_WIDTH || ${#ps1_dummy} -gt $((COLUMNS - PS1_COLUMNS_MARGIN)) ]] ); then
        if [[ -z $PS1_CONVERTER_NEW_LINE ]]; then
          PS1_CONVERTER_NEW_LINE=
          PS1_colorFormat PS1_CONVERTER_NEW_LINE - 'new-line' "${PS1_CFG_NEW_LINE:-${UNICODE_EXTRA_CHARS[new-line]} }"
        fi
        PS1+="\n$PS1_CONVERTER_NEW_LINE"
      fi;; # }}}
    hist) # {{{
      if [[ ! -z $BASH_PHISTORY_FILE && ! -z $HISTFILE && ( $HISTFILE == $HISTFILE_ORIG || $HISTFILE =~ .*/\.history(\.ign)?$ ) ]] && ! ${TMUX_POPUP:-false}; then
        :
      else
        PS1_colorFormat PS1 - 'hist' "$PS1_CFG_HIST" " "
      fi;; # }}}
    prompt) # {{{
      local sign='\$'
      # ${PS1_DEBUG:-false} && set -xv
      if [[ ! -n $PS1_PSTREE_INSTALLED ]]; then
        PS1_PSTREE_INSTALLED=true
        which pstree >/dev/null 2>&1 || PS1_PSTREE_INSTALLED=false
      fi
      if [[ ( ! -n $TMUX && $SHLVL -gt ${PS1_PROMPT_SHLVL_BASE:-1} ) || $SHLVL -gt 3 ]]; then
        local -n vSign="PS1_SIGN_$$"
        if [[ -z $vSign ]]; then
          vSign="$"
          local bashCnt=0
          if $PS1_PSTREE_INSTALLED; then
            local param="-a -s"
            $IS_MAC && param=
            local cmd="pstree $param -p $$ | sed -n --silent '1,/'$$'$/p'"
            if $IS_MAC; then
              cmd+=" | sed -n '/= \([0-9]\+\) .*bash$/s/.*= \([0-9]\+\) .*bash/\1/p'"
            else
              cmd+=" | sed -n -e ' /bash,1$/d' -e '/bash,[0-9]\+$/s/.*,//p'"
            fi
            cmd+=" | xargs -r ps -f -p | command grep -c -e 'bash'"
            if ${PS1_DEBUG:-false} || ${PS1_DEBUG2:-false}; then
              echoe "$cmd"
            fi
            bashCnt="$(eval $cmd)"
          else
            local p=$$ c=
            while true; do
              case "$(command ps -o cmd= $p)" in
              tmux\ *) break;;
              /bin/bash\ *) ;;
              *bash*)  bashCnt=$((bashCnt + 1));;
              esac
              p=$(echo $(command ps -o ppid= $p)) || break
              [[ $p == 1 || $p == 0 ]] && break
            done
          fi
          bashCnt=$((bashCnt - forDocker - ${PS1_EXTRA_BASH:-0}))
          if [[ $bashCnt -gt 1 ]]; then
            vSign='@'
            if ${BASH_USE_UNICODE_FOR_NESTED_BASH:-true}; then
              vSign="${UNICODE_EXTRA_CHARS[nested-bash]}" a=$((bashCnt - 1))
              [[ $a -gt 20 ]] && a=20
              vSign="$(printf "%d" "'$vSign")"
              vSign="$(printf "\U$(printf '%08x' "$((vSign+a-1))") ")"
            else
              [[ $((bashCnt - 1)) -gt 1 ]] && vSign+=$((bashCnt - 1))
            fi
          fi
        fi
        sign="$vSign"
      fi
      # ${PS1_DEBUG:-false} && set +xv
      PS1_colorFormat PS1 - "err-$__save_BASH_LAST_ERR" "$sign" " ";; # }}}
    cursor) # {{{
      PS1+="$(PS1_getColor 'cursor')";; # }}}
    esac; break; done
    PS0_time=0
    ${PS1_PROFILER:-false} && tt=$((${EPOCHREALTIME/[,.]} - $tt)) && echoe "step: $v: $tt"
  done
  PS1+="$cOff"
} # }}}
PS1_env() { # {{{
  local lastErr=$?
  set +xv
  case $1 in
  --save)
    __save_BASH_LAST_ERR=$lastErr
    __save_BASH_REMATCH=( "${BASH_REMATCH[@]}" );;
  --restore)
    lastErr=$__save_BASH_LAST_ERR
    BASH_REMATCH=( "${__save_BASH_REMATCH[@]}" )
    unset __save_BASH_REMATCH __save_BASH_LAST_ERR
    return $lastErr;;
  esac
} # }}}
ps1_toggle() { # @@ # {{{
  local i=
  local fullName=, shortName=
  local oldIFS=$IFS
  if [[ $1 == '@@' ]]; then # {{{
    case $3 in
    time | oneline | oneline-short)
      echo "on off";;
    *)
      local ret="next"
      ret+=" hl hn hr ht $(echo hist-{local,no,no-pers,restore,stat})"
      ret+=" split nl gt"
      ret+=" time-delta time-start time-curr td ts tc t-on t-off time t"
      ret+=" oneline oneline-short"
      for i in ${PS1_MODES[*]}; do
        IFS=':' read fullName shortName <<<"$i"
        ret+=" $fullName"
      done
      echo "$ret"
      ;;
    esac
    IFS=$oldIFS
    return 0
  fi # }}}
  # Toggles # {{{
  __ps1_var_toggle() {
    local -n v=$1
    ${v:-${2:-false}} && v=false || v=true
  }
  case $1 in
  time-* | td | tc | ts | t-on | t-off | time | t) # {{{
    case $1 in
    time | t)
      if [[ -z $2 ]]; then
        __ps1_var_toggle 'PS1_CFG_ADD_TIME_CURRENT' true
      else
        case $2 in
        false | off | 0) PS1_CFG_ADD_TIME_CURRENT=false;;
        true  | on  | 1) PS1_CFG_ADD_TIME_CURRENT=true;;
        esac
      fi
      if ! $PS1_CFG_ADD_TIME_CURRENT; then
        PS1_CFG_ORIG_ADD_TIME_DELTA=$PS1_CFG_ADD_TIME_DELTA
        PS1_CFG_ORIG_ADD_TIME_START=$PS1_CFG_ADD_TIME_START
        PS1_CFG_ADD_TIME_DELTA=false
        PS1_CFG_ADD_TIME_START=false
      else
        PS1_CFG_ADD_TIME_DELTA=${PS1_CFG_ORIG_ADD_TIME_DELTA:-false}
        PS1_CFG_ADD_TIME_START=${PS1_CFG_ORIG_ADD_TIME_START:-false}
      fi;;
    t-on | t-off)
      local v=true
      [[ $1 == "t-off" ]] && v=false
      PS1_CFG_ADD_TIME_DELTA=$v PS1_CFG_ADD_TIME_START=$v PS1_CFG_ADD_TIME_CURRENT=$v;;
    time-delta | td) __ps1_var_toggle 'PS1_CFG_ADD_TIME_DELTA';;
    time-start | ts) __ps1_var_toggle 'PS1_CFG_ADD_TIME_START';;
    time-curr  | tc) __ps1_var_toggle 'PS1_CFG_ADD_TIME_CURRENT';;
    esac
    return 0;; # }}}
  oneline | oneline-short) # {{{
    if [[ -z $2 ]]; then
      __ps1_var_toggle 'PS1_CFG_ADD_SPLIT' true
    else
      case $2 in
      false | off | 0) PS1_CFG_ADD_SPLIT=true;;
      true  | on  | 1) PS1_CFG_ADD_SPLIT=false;;
      esac
    fi
    if ${PS1_CFG_ADD_SPLIT:-true}; then
      ps1_toggle time ${PS1_CFG_ORIG_ADD_TIME_CURRENT:-true}
      case $1 in
      oneline-short)
        PS1_STATUS=${PS1_CFG_ORIG_STATUS:-short_git:default};;
      *)
        [[ -n $PS1_CFG_ORIG_STATUS ]] && PS1_STATUS=$PS1_CFG_ORIG_STATUS;;
      esac
    else
      PS1_CFG_ORIG_ADD_TIME_CURRENT=${PS1_CFG_ADD_TIME_CURRENT:-true}
      ps1_toggle time false
      case $1 in
      oneline-short)
        PS1_CFG_ORIG_STATUS=$PS1_STATUS
        PS1_STATUS="very_short:${PS1_STATUS#*:}";;
      esac
    fi
    return 0;; # }}}
  split) # {{{
    __ps1_var_toggle 'PS1_CFG_ADD_SPLIT' true
    return 0;; # }}}
  nl) # {{{
    __ps1_var_toggle 'PS1_CONVERTER_ADD_SEPARATOR' true
    return 0;; # }}}
  gt) # {{{
    if [[ -z $PS1_CFG_ADD_GIT ]]; then
      if ${TMUX_STATUS_RIGHT_GIT_STATUS:-true} && [[ -n $TMUX ]]; then
        PS1_CFG_ADD_GIT=true
      else
        PS1_CFG_ADD_GIT=false
      fi
    else
      __ps1_var_toggle 'PS1_CFG_ADD_GIT' true
    fi
    return 0;; # }}}
  hist-local | hist-no | hist-no-pers | hist-restore | hist-stat | hl | hn | ht | hr) # {{{
    local cmd="$1"
    if [[ "$cmd" == 'ht' ]]; then
      [[ ! -z $BASH_PHISTORY_FILE ]] && cmd='hn' || cmd='hr'
    fi
    case $cmd in
    hist-local | hl) # {{{
      [[ -z $BASH_ORIG_PHISTORY_FILE ]] && export BASH_ORIG_PHISTORY_FILE="$BASH_PHISTORY_FILE"
      [[ -z $BASH_ORIG_HISTFILE ]] && export BASH_ORIG_HISTFILE="$HISTFILE"
      [[ -z $BASH_ORIG_HISTIGNORE ]] && export BASH_ORIG_HISTIGNORE="$HISTIGNORE"
      unset BASH_PHISTORY_FILE
      export HISTFILE="$PWD/.history"
      [[ -e $PWD/.history.ign && ! -e $PWD/.history ]] && export HISTFILE="$PWD/.history.ign";; # }}}
    hist-no | hn) # {{{
      [[ -z $BASH_ORIG_PHISTORY_FILE ]] && export BASH_ORIG_PHISTORY_FILE="$BASH_PHISTORY_FILE"
      [[ -z $BASH_ORIG_HISTFILE ]] && export BASH_ORIG_HISTFILE="$HISTFILE"
      [[ -z $BASH_ORIG_HISTIGNORE ]] && export BASH_ORIG_HISTIGNORE="$HISTIGNORE"
      unset BASH_PHISTORY_FILE HISTFILE HISTIGNORE;; # }}}
    hist-no-pers) # {{{
      [[ -z $BASH_ORIG_PHISTORY_FILE ]] && export BASH_ORIG_PHISTORY_FILE="$BASH_PHISTORY_FILE"
      unset BASH_PHISTORY_FILE;; # }}}
    hist-restore | hr) # {{{
      [[ ! -z $BASH_ORIG_PHISTORY_FILE ]] && export BASH_PHISTORY_FILE="$BASH_ORIG_PHISTORY_FILE"
      [[ ! -z $BASH_ORIG_HISTFILE ]] && export HISTFILE="$BASH_ORIG_HISTFILE"
      [[ ! -z $BASH_ORIG_HISTIGNORE ]] && export HISTIGNORE="$BASH_ORIG_HISTIGNORE"
      unset BASH_ORIG_PHISTORY_FILE BASH_ORIG_HISTFILE BASH_ORIG_HISTIGNORE;; # }}}
    esac
    history -r
    [[ ${#cmd} == 2 ]] && return 0
    echoe "ph=[$BASH_PHISTORY_FILE]"
    echoe "hi=[$HISTFILE]"
    return 0;; # }}}
  esac # }}}
  local current=
  local next=
  IFS=':' read current next <<<"$PS1_STATUS"
  if [[ ! -z $1 ]]; then # {{{
    next=
    if [[ $1 == 'next' ]]; then
      next="next"
    else
      for i in ${PS1_MODES[*]}; do
        IFS=':' read fullName shortName <<<"$i"
        [[ $1 == $fullName || $1 == $shortName ]] && next="$fullName" && break
      done
    fi
    IFS=$oldIFS
    [[ -z $next ]] && return 1
    [[ $next == $current ]] && return 0
  fi # }}}
  if [[ $next == 'next' ]]; then # {{{
    for i in ${!PS1_MODES[*]}; do
      IFS=':' read fullName shortName <<<"${PS1_MODES[$i]}"
      if [[ $current == $fullName ]]; then
        i=$(( ($i + 1) % ${#PS1_MODES[*]}))
        IFS=':' read fullName shortName <<<"${PS1_MODES[$i]}"
        next=$fullName
        break
      fi
    done
    (
      import-module echor
      echormf -C 0 "Changing PS1 to %yellow:{$next}"
    )
  fi # }}}
  unset ${!PS1_CACHE_*}
  PS1_STATUS="$next:$current"
  IFS=$oldIFS
} # }}}
ps1_fix() { # {{{
  local current=${PROMPT_COMMAND[0]}
  unset PROMPT_COMMAND
  PROMPT_COMMAND=$PROMPT_COMMAND_ORIG
  [[ $current != PS1_setter* ]] && PROMPT_COMMAND+="; $current"
  PROMPT_COMMAND
} # }}}

alias pt='ps1_toggle' # @@
alias gt='ps1_toggle gt'
alias pth='ps1_toggle ht'
