#!/usr/bin/env bash
# vim: fdl=0

bash-on-list() { # @@ # {{{
  if [[ $1 == '@@' ]]; then # {{{
    echo "--always --cont --pre --post --no-bash DIRS"
    return 0
  fi # }}}
  local exitOnErr=true preCmd= postCmd= always=false skipBash=false
  while [[ ! -z $1 ]]; do # {{{
    case $1 in
    --always)  always=true;;
    --cont)    exitOnErr=false;;
    --pre)     preCmd="$2"; shift;;
    --post)    postCmd="$2"; shift;;
    --no-bash) skipBash=true;;
    *)         break;;
    esac; shift
  done # }}}
  local list="$@"
  [[ ! -z $list ]] || return 1
  local d= oPWD="$OLDPWD" retVal=0
  for d in $list; do # {{{
    local err=0
    command cd "$d" >/dev/null 2>&1 || { echoe -f "Cannot cd to '$d', skipping"; continue; }
    [[ -z $preCmd ]] || eval "$preCmd"
    err=$?
    if [[ $err == 0 ]] || $always; then
      $skipBash || bash </dev/tty
      err=$?
    fi
    if [[ ! -z $postCmd ]] && ( [[ $err == 0 ]] || ! $exitOnErr ); then # {{{
      eval "$postCmd"
      err=$?
    fi # }}}
    command cd - >/dev/null 2>&1
    if [[ $err != 0 ]]; then
      retVal=1
      $exitOnErr && break
    fi
  done # }}}
  OLDPWD="$oPWD"
  return $retVal
} # }}}
bash-trace() { # @@ # {{{
  set +x
  if [[ $1 == '@@' ]]; then # {{{
    case $3 in
    -f | --file) echo "FILE";;
    --fd)        echo "FD";;
    *)           echo "-f --file --fd --new start stop follow help";;
    esac
    return 0
  fi # }}}
  import-module time-tools
  local file= mode= xtraceFD=3 new=false local mS='{' mE='}'
  while [[ ! -z $1 ]]; do # {{{
    case $1 in
    -f | --file) file="$2"; shift;;
    --fd)        xtraceFD="$2"; shift;;
    --new)       new=true;;
    help) # {{{
      echo "start : exec 3>>a-file; export BASH_XTRACEFD=3; set -x"
      echo "stop  : set +x; exec 3>&-; unset BASH_XTRACEFD";; # }}}
    start | stop | follow)
      mode="$1";;
    esac; shift
  done # }}}
  if [[ -z "$file" ]]; then # {{{
    file="$TMP_MEM_PATH/trace.$PPID.log"
    [[ ! -e "$file" ]] && echoe -f "Tracing into $file"
  fi # }}}
  case $mode in
  start) # {{{
    if $new; then # {{{
      rm -f "$file"
      (
        echo "# vim: fdl=0 ft=default"
        echo
      ) >"$file"
    fi # }}}
    local no=1
    [[ -e $file ]] && no="$(( $(command grep -c "trace#[0-9]\+ # {\{3\}" "$file") + 1 ))"
    echo "$(time2s now): trace#$(printf "%02d" "$no") # $mS$mS$mS" >>"$file"
    eval "exec $xtraceFD>>\"$file\""
    export BASH_XTRACEFD=$xtraceFD
    set -x;; # }}}
  stop) # {{{
    eval "exec $BASH_XTRACEFD>&-"
    unset BASH_XTRACEFD
    local no=1
    [[ -e  "$file" ]] && no="$(( $(command grep -c "trace#[0-9]\+ # {\{3\}" "$file") ))"
    echo "$(time2s now): trace#$(printf "%02d" "$no") # $mE$mE$mE" >>"$file";; # }}}
  follow) # {{{
    if [[ $file == '-' ]]; then
      file="$(get-file-list -t -1 "$TMP_MEM_PATH/trace.*.log")"
      [[ -e $file ]] && echoe -f "Following $(basename "$file")"
    fi
    if [[ ! -e $file && $file != /* && $file != ./* ]]; then # {{{
      if [[ -e "$TMP_MEM_PATH/$file" ]]; then
        file="$TMP_MEM_PATH/$file"
      elif [[ -e "$TMP_MEM_PATH/trace.$file.log" ]]; then
        file="$TMP_MEM_PATH/trace.$file.log"
      elif [[ -e "$TMP_MEM_PATH/trace.%$file.log" ]]; then
        file="$TMP_MEM_PATH/trace.%$file.log"
      fi
    fi # }}}
    tail -F "$file";; # }}}
  *) # {{{
    echoe -f "Wrong mode [$mode]"; return 1;; # }}}
  esac
} # }}}
byebye() { # {{{
  local ask=true overSSH=false pid= ip= sessionId=$XDG_SESSION_ID
  [[ $1 == '-' ]] && ask=false && shift
  if [[ -n $TMUX ]]; then
    pid=$($ENV_SCRIPTS/tmux/tm.sh --is-ssh --pid) && overSSH=true
  elif [[ -n $SSH_CONNECTION ]]; then
    overSSH=true
    ip=$(echo $SSH_CONNECTION | awk '{print $1}')
  fi
  $overSSH || return 1
  if [[ -z $ip ]]; then
    [[ -e /proc/$pid/environ ]] || return 1
    read ip _ < <(strings /proc/$pid/environ | sed -n '/^SSH_CONNECTION=/s/.*=//p')
    read sessionId _ < <(strings /proc/$pid/environ | sed -n '/^XDG_SESSION_ID=/s/.*=//p')
  fi
  [[ -n "$ip" ]] || return 1
  if ${BYEBYE_DO_SUSPEND:-true}; then
    ! $ask || progress --msg "suspend & log off" --wait 3s --key || return 0
    if ${UTILS_SUSPEND_USE_PWR_MGR:-false} && is-installed -w power-manager.sh; then
      ( sleep 5 && power-manager.sh --now ) &
      disown
    else
      ( sleep 5 && suspend ) &
      disown
    fi
  fi
  local session= status=
  while read session _ _ _ _ state _; do
    [[ "$session" != "$sessionId" ]] || continue
    local sessionIp=$(loginctl show-session "$session" -p RemoteHost --value)
    [[ -n $sessionIp ]] || continue
    [[ "$sessionIp" == "$ip" ]] || continue
    loginctl session-status $session | grep -q "tmux.*new-session" && continue
    case $state in
    active) loginctl terminate-session "$session";;
    esac
    loginctl kill-session "$session" 2>/dev/null
  done < <(loginctl list-sessions --no-legend)
  if [[ -n $TMUX ]]; then
    echo $TMUX_SESSION > $TMP_PATH/.tmux_last_session.$USER
    tmux detach -P
  else
    command logout 2>/dev/null || command exit
  fi
} # }}}
change-monitor() { # @@ # {{{
  $ENV_SCRIPTS/small-utils/change-monitor.sh "$@"
} # }}}
clean-ansi() { # {{{
  if [[ ! -z $1 ]]; then
    echo -e "$@"
  else
    command cat -
  fi | sed -u -e 's/\x1b\[[0-9;]\+[mMGK]//g' -e 's/\x1b\[[Jm]//g'
} # }}}
clr() { # @@ # {{{
  local scr=true reset=false hist=false
  if [[ $1 == '@@' ]]; then
    local ret=""
    $scr   && ret+=" --no-scr"   || ret+=" --scr"
    $reset && ret+=" --no-reset" || ret+=" --reset"
    if [[ -n $TMUX ]]; then
      $hist && ret+=" --no-hist" || ret+=" --hist"
    fi
    echo "$ret"
    return 0
  fi
  while [[ ! -z $1 ]]; do
    case $1 in
      --reset)    reset=true;;
      --no-reset) reset=false;;
      --scr)      scr=true;;
      --no-scr)   scr=false;;
      --hist)     hist=true;;
      --no-hist)  hist=false;;
    esac
    shift
  done
  if $scr; then
    $reset && reset || clear -x
  fi
  if $hist && [[ -n $TMUX ]]; then
    tmux clear-history
  fi
  unset PS1_CONVERTER_ADD_SEPARATOR
  return 0
} # }}}
Exit() { # {{{
  if [[ ! -n $TMUX ]]; then
    command exit $@
  else
    local title="$TMUX_SESSION"
    tmux detach -P
    tmux kill-session -t $title
  fi
} # }}}
fix-agent() { # @@ # {{{
  if [[ $1 == '@@' ]]; then
    echo "start-if start-iff fix -c check"
    return 0
  fi
  local err=0
  case $1 in
  '' | -c | --check)
    local keys=
    keys="$(ssh-add -l 2>/dev/null)" || keys=
    [[ ! -z $keys ]] && echoe -f "$SSH_AGENT_PID: $(echo -e "$keys" | awk '{print $3}' | sort | tr '\n' ' ')" && return 0
    source $SCRIPT_PATH/bin/fix-ssh-agent.sh start-if
    err=$?; unset __fsa_err
    [[ $err == 0 ]] || eval $(die $err fix-agent "cannot start ssh-agent")
    keys="$(ssh-add -l)" || keys=
    [[ ! -z $keys ]] && echoe -f "$SSH_AGENT_PID: $(echo -e "$keys" | awk '{print $3}' | sort | tr '\n' ' ')" && return 0
    if [[ ! -z $SSH_KEYS ]]; then
      sshh-add --keys $SSH_KEYS
      keys="$(ssh-add -l)" || keys=
    fi
    [[ ! -z $keys ]] && echoe -f "$SSH_AGENT_PID: $(echo -e "$keys" | awk '{print $3}' | sort | tr '\n' ' ')" && return 0
    echoe -f "$SSH_AGENT_PID: no keys installed"
    return;;
  esac
  source $SCRIPT_PATH/bin/fix-ssh-agent.sh "$@"
  err=$?; unset __fsa_err
  return $err
} # }}}
fix_caps() { # {{{
  which setxkbmap >/dev/null 2>&1 && setxkbmap -option 'caps:ctrl_modifier'
  if which xcape >/dev/null 2>&1; then
    killall xcape >/dev/null 2>&1
    xcape -e "${CAPS_KEY:-Caps_Lock}=Escape"
  fi
} # }}}
for-do() { # {{{
  if [[ $1 == '@@' ]]; then # {{{
    echo "- -l"
    return 0
  fi # }}}
  local arg= cmd= xargsP="-n1 -r" wasBracketParam=false processWords=false
  while [[ ! -z $1 ]]; do # {{{
    case $1 in
    -)  xargsP+=" -I{}"; wasBracketParam=true;;
    -w) processWords=true;;
    *)  break;;
    esac; shift
  done # }}}
  if [[ ! -t 0 ]]; then # {{{
    arg="$(<-)"
    cmd="$@" # }}}
  elif [[ "$@" == *\ --\ * ]]; then # {{{
    arg="$@"
    cmd="$@"
    args="$(echo "${arg/ -- *}" | sed -e 's/^\s\+//' -e 's/\s\+$//')"
    cmd="$( echo "${cmd/* -- }" | sed -e 's/^\s\+//' -e 's/\s\+$//')" # }}}
  else # {{{
    arg="$1"
    shift
    cmd="$@"
  fi # }}}
  ! $wasBracketParam && [[ $cmd == *{}* ]] && xargsP+=" -I{}"
  echo -n "$arg" | { if $processWords; then sed 's/ /\n/g'; else command cat -; fi; } | sed '/^\s*$/d' | eval xargs $xargsP $cmd
} # }}}
fr() { # @@:new # {{{
  if [[ $1 == '@@' ]]; then # {{{
    tmux list-panes -a -F '#S:#I.#P'
    tmux list-panes -s -F ':#I.#P'
    tmux list-panes -F '.#P'
    echo "@@-d"
    return 0
  fi # }}}
  local from= fromPane=
  if [[ -z $1 && -e $FROM ]]; then # {{{
    [[ -t 1 ]] || { echo "$FROM"; return 0; }
    declare -a pwdFro= pwdPwd=
    pwdFro=( $(echo -n "${FROM/$HOME/\~}" | awk -v RS='/' -v ORS=' ' '{print}') )
    pwdPwd=( $(echo -n "${PWD/$HOME/\~}"  | awk -v RS='/' -v ORS=' ' '{print}') )
    local i=
    for ((i=0; i < ${#pwdFro[*]}; ++i)); do
      [[ ${pwdFro[$i]} == ${pwdPwd[$i]} ]] && continue
      pwdFro[$i]="${CYellow}${pwdFro[$i]}"
      break
    done
    printf "/%s" "${pwdFro[@]}" | sed 's|^/~|~|'
    printf "${COff}\n"
    return 0
  fi # }}}
  while [[ ! -z $1 ]]; do # {{{
    case $1 in
    -t) shift; fromPane=$1; from=$(tmux display-message -t $fromPane -p -F '#{pane_current_path}');;
    *)
      if [[ -d $1 ]]; then
        from="$1"
        break
      else
        fromPane="$1"
        from=$(tmux display-message -t $fromPane -p -F '#{pane_current_path}')
      fi;;
    esac; shift
  done # }}}
  if [[ -t 1 ]]; then # {{{
    if [[ -z $from ]]; then
      from="$PWD"
      echo "export FROM=\"$from\"; F=\"$from\"; FROM_PANE=\"${fromPane:-$TMUX_PANE}\"" | tee >(xclip --put)
    else
      export FROM="$from"
      export F="$FROM"
      export FROM_PANE="${fromPane:-$TMUX_PANE}"
    fi # }}}
  else # {{{
    echo "${from:-$PWD}"
  fi # }}}
} # }}}
getCurPos() { # {{{
  local p=
  read -sdR -p $'\E[6n' pos # ]
  echo "${pos#*\[}" # ]
} # }}}
logout() { # {{{
  if [[ ! -n $TMUX ]]; then
    command logout 2>/dev/null || command exit
  else
    echo $TMUX_SESSION > $TMP_PATH/.tmux_last_session.$USER
    tmux detach -P
  fi
} # }}}
mapShortCutToFull() { # @@ # {{{
  if [[ $1 == '@@' ]]; then # {{{
    echo "-a --all PREFIX SET"
    return 0
  fi # }}}
  local allDisplay=false
  while [[ ! -z $1 ]]; do # {{{
    case $1 in
    -a | --all) allDisplay=true;;
    *) break;;
    esac; shift
  done # }}}
  local shortcut=$1 set=$2 i= onlyOne=true foundFull= allMatches=
  for i in $(echo "$set" | tr ' ' '\n'); do # {{{
    [[ $i == $shortcut ]] && echo "$i" && return 0
    if [[ $i =~ ^$shortcut.* ]]; then
      if [[ -z $foundFull ]]; then
        allMatches+="$i "
        foundFull=$i
      else
        allMatches+="$i "
        onlyOne=false
      fi
    fi
  done # }}}
  if [[ ! -z $foundFull ]]; then # {{{
    if $onlyOne; then
      echo "$foundFull"
    elif $allDisplay; then
      echo "$allMatches"
      return 1
    fi
  fi # }}}
} # }}}
restore() { # @@ # {{{
  if [[ $1 == @@ ]]; then
    echo "-?"
    return 0
  fi
  local captureFile=$CAPTURE_FILE
  if [[ -z $CAPTURE_FILE ]]; then
    captureFile="$TMP_MEM_PATH/capture.txt"
    [[ -n $TMUX ]] && captureFile="$TMP_MEM_PATH/capture-$(tmux display-message -pF '#S-#W').txt"
  fi
  [[ -e ./cap.tmp~ ]] && captureFile="./cap.tmp~"
  [[ $1 == '-?' ]] && echo "$captureFile" && return 0
  [[ -e $captureFile ]] || return 1
  /bin/cat $captureFile
}
export PHISTORY_IGNORED_COMMANDS+=":capture:restore" # }}}
rpath() { # {{{
  local pwd="." src= p="-s"
  while [[ ! -z $1 ]]; do # {{{
    case $1 in
    --pwd) pwd=$2; shift;;
    -*)    p+="$1 ";;
    +s)    p="${p/-s}";;
    *) break;;
    esac; shift
  done # }}}
  src=$1 pre=
  [[ -z $src ]] && return 1
  [[ $src == $pwd* ]] && pre="./"
  echo "$pre$(realpath $p --relative-to "$pwd" "$src")"
} # }}}
sudo() { # {{{
  if [[ ! -z $1 ]]; then
    command sudo $@
  else
    command sudo --preserve-env=HOME -s
  fi
} # }}}
up() { # {{{
  is-installed up || { echoe -f "up not installed"; return 1; }
  ( TERM='xterm-256color' command up "$@" )
} # }}}
zipf() { # {{{
  [ -d "$1" ] && zip -r $1.zip $@ && return 0
  [ "$1" == '-' ] && shift && zip -r $1.zip $@ && return 0
  while [ -f "$1" ]; do gzip $1; shift; done
} # }}}
# OS specifics # {{{
if ! $IS_MAC; then
  wifi-tool() { # {{{
    if [[ $1 == '@@' ]]; then # {{{
      case ${4:-$3} in
      -c | --connect | conn | c | connect)
        case $2 in
        2)     echo "- $WIFI_DEFAULT_NETWORK";;
        2 | 3) echo "- $WIFI_DEFAULT_BBSIDS";;
        esac;;
      *) echo "-l --list -c --connect l c";;
      esac
      return 0
    fi # }}}
    local cmd=${1:-list}
    shift
    cmd=${cmd#-}; cmd=${cmd#-}
    case $cmd in
    l | list) # {{{
      nmcli d wifi list --rescan yes;; # }}}
    c | conn | connect) # {{{
      local ssid=$WIFI_DEFAULT_NETWORK bssid=
      case $1 in # {{{
      '') ;;
      -)  bssid="-"; shift;;
      *)  ssid=$1; shift;;
      esac # }}}
      [[ -z $ssid ]] && echoe -f "No SSID" && return 1
      if [[ ! -z $1 ]]; then # {{{
        bssid=$1
      elif [[ $bssid == '-' ]]; then
        bssid=
      else
        local wifiId="$(echo "$ssid" | sha1sum | cut -c1-7)"
        local bssidId=WIFI_DEFAULT_BSSID_$wifiId
        local -n bssidVal=$bssidId
        bssid=$bssidVal
      fi # }}}
      echoe -f "Getting bssids for $ssid"
      local networks="$(nmcli d wifi list --rescan yes | awk "/ $ssid /")"
      [[ -z $networks ]] && echoe -f "No bssids for $ssid" && return 1
      local bssidCurrent="$(echo "$networks" | awk '/^\*/ {print $2}')"
      [[ -z $bssid ]] && bssid="$(echo "$networks" | cut -c4- | head -n1 | awk '{print $1}')"
      if [[ $bssid == $bssidCurrent ]]; then
        echoe -f "Already connected to $ssid on AP $bssid"
      else
        echoe -f "Connecting to $ssid on AP $bssid"
        nmcli d wifi connect $bssid
      fi;; # }}}
    esac
  }
  COMPLETION_GENERIC_FUNCTIONS+=" wifi-tool" # }}}
else
  wifi-tool() { # {{{
    echoe -f "Not implemented"
  } # }}}
fi
# }}}
export -f bash-trace change-monitor clean-ansi mapShortCutToFull rpath

