[ids]
*

[main]
capslock = overloadt(control, esc, 150)

[meta]
a = C-a
c = C-c
v = C-S-v
x = C-x
z = C-z
t = C-t
w = C-w
backspace = delete
[ = C-S-tab
] = C-tab

[meta+shift]
a = M-S-a
c = M-S-c
v = M-S-v
x = M-S-x
z = M-S-z
t = M-S-t
w = M-S-w
