# generated as:
# ./conv.sh "a" "Alt" "$(./conv.sh --get 'a-z')"
# ./conv.sh "-=[]\\;',/" "Alt|Shift" "$(./conv.sh --get 'left+s')"

[[keyboard.bindings]]
chars = "\u2039" # ‹
key = "Key3"
mods = "Alt|Shift"
[[keyboard.bindings]]
chars = "\u203a" # ›
key = "Key4"
mods = "Alt|Shift"

[[keyboard.bindings]]
key = "Q"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "W"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "W"
mods = "Command|Shift"
action = "Quit"
