#!/usr/bin/env bash
# vim: fdl=0

fzf-exe() { # @@ # {{{
  $ALIASES_SCRIPTS/fzf-tools/fzf-exe.sh "$@"
} # }}}
fzfwr() { # {{{
  local isInputRc=false
  [[ $1 == 'iRC' ]] && isInputRc=true && shift
  local fdfindCmd="fdfind"
  is-installed -w $fdfindCmd >/dev/null 2>&1 || fdfindCmd="fd"
  is-installed -w $fdfindCmd >/dev/null 2>&1 || fdfindCmd=
  if [[ -n $fdfindCmd ]]; then
    local cmd="$fdfindCmd -d ${FZF_MAX_DEPTH:-8}"
  else
    cmd="command find -L . -mindepth 1 -maxdepth 8 \( -path '*/\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \) -prune -o -type f -print -o -type l -print 2>/dev/null | cut -b3-"
  fi
  cmd+=" | sort"
  local selected="$(__fzf_select__ --cmd "$cmd" --handler __fzf_handler_fs "$@")" # | sed 's/^\|$/"/g' | tr '\n' ' ' | sed 's/ \+/ /')"
  [[ -n $selected ]] || return 0
  if $isInputRc; then
    READLINE_LINE="${READLINE_LINE:0:$READLINE_POINT}$selected${READLINE_LINE:$READLINE_POINT}"
    READLINE_POINT=$(( READLINE_POINT + ${#selected} ))
  else
    echo "$selected"
  fi
} # }}}
__env_fzf_autocomplete__() {
  compgen -v \
  | grep "^[A-Z]" \
  | fzf +m --sort \
      --prompt 'env> ' \
      --preview 'eval echo \${1}' \
      --preview-window 'nohidden'
}
__env_fzf_autocomplete_inline__() {
  local selected="$(__env_fzf_autocomplete__)"
  [[ ! -z $selected ]] || return 1
  selected="\$$selected"
  READLINE_LINE="${READLINE_LINE:0:$READLINE_POINT}$selected${READLINE_LINE:$READLINE_POINT}"
  READLINE_POINT=$((READLINE_POINT + ${#selected}))
}

export -f fzf-exe fzfwr

export PHISTORY_IGNORED_COMMANDS+=":ff:fzfwr:vimf:vimg:vims"
