#!/usr/bin/env bash
# vim: fdl=0

fzf-exe() { # @@ # {{{
  $ALIASES_SCRIPTS/fzf-tools/fzf-exe.sh "$@"
} # }}}
fzfwr() { # {{{
  local isInputRc=false
  [[ $1 == 'iRC' ]] && isInputRc=true && shift
  local cmd="fdfind -d ${FZF_MAX_DEPTH:-8}"
  if ! which ${cmd%% *} >/dev/null 2>&1; then
    cmd="command find -L . -mindepth 1 -maxdepth 8 \( -path '*/\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \) -prune -o -type f -print -o -type l -print 2>/dev/null | cut -b3-"
  fi
  cmd+=" | sort"
  local selected="$(__fzf_select__  --cmd "$cmd" "$@")" # | sed 's/^\|$/"/g' | tr '\n' ' ' | sed 's/ \+/ /')"
  if $isInputRc; then
    READLINE_LINE="${READLINE_LINE:0:$READLINE_POINT}$selected${READLINE_LINE:$READLINE_POINT}"
    READLINE_POINT=$(( READLINE_POINT + ${#selected} ))
  else
    echo "$selected"
  fi
  return 0
} # }}}
vimf() { # @@ # {{{
  $ALIASES_SCRIPTS/fzf-tools/vimf.sh "$@"
  set +f
} # }}}
export -f fzf-exe fzfwr

export PHISTORY_IGNORED_COMMANDS+=":ff:fzfwr:vimf:vimg:vims"
