#!/usr/bin/env bash
# vim: fdl=0
# env:  ! install 'output_to_file' && TO_INSTALL+=' output_to_file '

grep_wrapper() { # @@ # {{{
  if [[ $1 == '@@' ]]; then
    echo "+tee=true +tee=false +fzf +-fzf"
    echo +c={Gray,Red,Green,Yellow,Blue,Pink,Cyan,Gold,Hls,Search}
    return 0
  fi
  [[ $1 != --cmd-* && $1 != +tee* ]] && { command grep "$@";  return $?; }
  [[ $1 == --cmd-* && $2 != +tee* && ${#BASH_SOURCE[*]} != 1 ]] && shift && { command grep "$@"; return $?; }
  local params="$GREP_DEFAULT_PARAMS -s"
  local cmd="grep"
  local args=
  local oldColors=$GREP_COLORS
  local gnuGrep="$(command grep --version | head -n1 | command grep -q 'GNU' && echo 'true' || echo 'false')"
  $IS_MAC && ! $gnuGrep && oldColors=$GREP_COLOR
  local color=
  local use_tee=
  local ignoreErr=
  local query="${@: -2}"
  local fzf_params=
  local fzf_prompt=
  local use_fzf="$(echo ",$FZF_USAGE," | command grep -o ',\s*GREP:[^,]\+,' | command grep -o 'true\|false')"
  [[ -z $use_fzf ]] && use_fzf=$FZF_INSTALLED
  while [[ ! -z $1 ]]; do # {{{
    case $1 in
      --cmd-*) cmd=${1/"--cmd-"}
                case $cmd in
                zgrep) ignoreErr='--ignore-err';;
                esac;;
      +c=*)    color=${1/"+c="};;
      +c)      color=$2; shift;;
      +c*)     color=${1/"+c"};;
      +tee=*)  use_tee=${1/+tee=};;
      +tee)    use_tee=true;;
      +-fzf | +-f) use_fzf=false;;
      +fzf  | +f)  use_fzf=$FZF_INSTALLED;;
      +fzf-prompt) fzf_prompt="$2"; shift;;
      +fzf=*)  use_fzf=${1/+fzf=}; $use_fzf && use_fzf=$FZF_INSTALLED;;
      +fzf-*)  fzf_params+=" $1";;
      -*)      args+=" $1";;
      *)       args+=" \"$1\"";;
    esac
    shift
  done # }}}
  if [[ ! -z $color ]]; then # {{{
    params+=" --color=yes"
    case $(echo ${color,,}) in
    gr|gray|grey)   GREP_COLORS=$(echo $GREP_COLORS | sed 's/mt=[0-9;]*/mt=01;30/');;
    r|red)          GREP_COLORS=$(echo $GREP_COLORS | sed 's/mt=[0-9;]*/mt=01;31/');;
    g|green)        GREP_COLORS=$(echo $GREP_COLORS | sed 's/mt=[0-9;]*/mt=01;32/');;
    y|yellow)       GREP_COLORS=$(echo $GREP_COLORS | sed 's/mt=[0-9;]*/mt=01;33/');;
    b|blue)         GREP_COLORS=$(echo $GREP_COLORS | sed 's/mt=[0-9;]*/mt=01;34/');;
    p|pink)         GREP_COLORS=$(echo $GREP_COLORS | sed 's/mt=[0-9;]*/mt=01;35/');;
    c|cyan)         GREP_COLORS=$(echo $GREP_COLORS | sed 's/mt=[0-9;]*/mt=01;36/');;
    gold)           GREP_COLORS=$(echo $GREP_COLORS | sed 's/mt=[0-9;]*/mt=38;5;220/');;
    hls)            GREP_COLORS=$(echo $GREP_COLORS | sed 's/mt=[0-9;]*/mt=38;5;208/');;
    search)         GREP_COLORS=$(echo $GREP_COLORS | sed 's/mt=[0-9;]*/mt=38;5;214/');;
    [0-9]*\;[0-9]*) GREP_COLORS=$(echo $GREP_COLORS | sed "s/mt=[0-9;]*/mt=$color/");;
    [0-9]*)         GREP_COLORS=$(echo $GREP_COLORS | sed "s/mt=[0-9;]*/mt=01;38;5;$color/");;
    *=*)            GREP_COLORS=$(echo $GREP_COLORS | sed "s/mt=[0-9;]*/$color/");;
    esac
  fi # }}}
  export GREP_COLORS
  $IS_MAC && ! $gnuGrep && export GREP_COLOR=${GREP_COLORS/mt=}
  local exclude=
  [[ -t 0 && $cmd != z* ]] && exclude=" --exclude-dir .git --exclude-dir .hg --exclude=tags --exclude 'cscope*' $GREP_EXCLUDES"
  if [[ -t 0 ]]; then # {{{
    [[ $args != *-h* ]] && params+=" -Hn"
  fi # }}}
  if [[ -z $use_tee ]]; then # {{{
    [[ -t 0 ]] && use_tee=true || use_tee=false
  fi # }}}
  local err=
  if [[ ! -t 1 ]]; then # {{{
    use_fzf=false
    params="${params/--color=yes}"
    params="${params/--color}"
    params+=" --color=no "
  fi # }}}
  if $use_tee; then # {{{
    params=" $params "
    [[ -t 1 ]] && params="${params/--color }" && params="--color=$($use_fzf && echo 'no' || echo 'yes') $params"
  fi # }}}
  set - "$args"
  # echo "output_to_file $use_tee +fzf=$use_fzf $ignoreErr "eval $cmd" $params "$@" $exclude" >/dev/stderr
  [[ -z fzf_prompt ]] && fzf_prompt="grep: $query> "
  output_to_file --no-sort $use_tee +fzf=$use_fzf +fzf-p "--prompt '$fzf_prompt'" $fzf_params $ignoreErr "eval $cmd" $params "$@" $exclude
  err=$?
  export GREP_COLORS=$oldColors
  $IS_MAC && ! $gnuGrep && export GREP_COLOR=$oldColors
  return $err
} # }}}

alias grep='grep_wrapper --cmd-grep' # @@
alias egrep='grep_wrapper --cmd-egrep'
alias fgrep='grep_wrapper --cmd-fgrep'
alias zgrep='grep_wrapper --cmd-zgrep'
alias zegrep='grep_wrapper --cmd-zegrep'
alias zfgrep='grep_wrapper --cmd-zfgrep'
alias _grep='grep_wrapper --cmd-grep +tee=false'
alias cgrep='command grep'

