#!/usr/bin/env bash
# vim: fdl=0
# env:  ! install 'output_to_file' && TO_INSTALL+=' output_to_file '

mg() { # @@ # {{{
  if [[ $1 == @@ ]]; then
    echo "+g +ack +ag +rg +tee=true +tee=false +-fzf +fzf"
    return 0
  fi
  local cmd="ag"
  ! which $cmd >/dev/null 2>&1 && cmd="rg"
  ! which $cmd >/dev/null 2>&1 && cmd="ack"
  ! which $cmd >/dev/null 2>&1 && cmd="grep"
  local tee=true
  local use_fzf="$(echo ",$FZF_USAGE," | command grep -o ',\s*MG:[^,]\+,' | command grep -o 'true\|false')"
  local fzf_params=
  [[ -z $use_fzf ]] && use_fzf=$FZF_INSTALLED
  while [[ ! -z $1 ]]; do
    case $1 in
    +g)     cmd="grep";;
    +ack)   cmd="ack";;
    +ag)    cmd="ag";;
    +rg)    cmd="rg";;
    +tee=*) tee="${1/+tee=}";;
    +-fzf | +-f) use_fzf=false;;
    +fzf  | +f)  use_fzf=$FZF_INSTALLED;;
    +fzf=*)      use_fzf=${1/+fzf=}; $use_fzf && use_fzf=$FZF_INSTALLED;;
    +fzf-*)      fzf_params+=" $1";;
    *)      break;;
    esac
    shift
  done
  _aliases_dbg $cmd "$@"
  _aliases_dbg
  local err=
  case $cmd in
  grep*) grep_wrapper   --cmd-grep +tee=$tee +fzf=$use_fzf $fzf_params -R "$@" *; err=$?;;
  ack*)  ack_ag_wrapper --cmd-ack  +tee=$tee +fzf=$use_fzf $fzf_params    "$@"  ; err=$?;;
  ag*)   ack_ag_wrapper --cmd-ag   +tee=$tee +fzf=$use_fzf $fzf_params    "$@"  ; err=$?;;
  rg*)   ack_ag_wrapper --cmd-rg   +tee=$tee +fzf=$use_fzf $fzf_params    "$@"  ; err=$?;;
  esac
  return $err
} # }}}

alias _mg='mg +tee=false' # @@

