#!/usr/bin/env bash
# vim: fdl=0

mutex-init() { # @@ # {{{
  if [[ $1 == '@@' ]]; then # {{{
    echo "--auto-clean-after --no-trap --clean-on-start --dbg"
    return 0
  fi # }}}
  [[ -z $1 ]] && echo "Mutex not specified" >/dev/stderr && return 1
  local LOCK_DIR="$MEM_KEEP/locks"
  local newMutex="$1"
  [[ $newMutex != ./* && $newMutex != /* ]] && newMutex="$LOCK_DIR/$newMutex"
  [[ ! -z $MUTEX_LOCK_FILE && $MUTEX_LOCK_FILE != $newMutex ]] && echo "Mutex already set [${MUTEX_LOCK_FILE/*\/}], nested mutexes are not allowed" >/dev/stderr && return 1
  export MUTEX_LOCK_FILE="$newMutex"
  mutex-dbg() { # {{{
    $MUTEX_DBG && echo "${MUTEX_LOCK_FILE/*\/} $(command date +"$DATE_FMT") $@" >/dev/stderr
  } # }}}
  mutex-lock() { # {{{
    local timeout=${1:-0}
    mutex-dbg "Locking (wait=$timeout)"
    if [[ -e $MUTEX_LOCK_FILE && $MUTEX_ACCESS_MIN_DELTA -gt 0 ]]; then
      local accessTime=$(command stat -c %Y $MUTEX_LOCK_FILE)
      local currentTime="${EPOCHSECONDS:-$(epochSeconds)}"
      mutex-dbg "Mutex already exists, (at=$accessTime, ct=$currentTime, d=$MUTEX_ACCESS_MIN_DELTA)"
      if [[ $(($accessTime + $MUTEX_ACCESS_MIN_DELTA)) -lt $currentTime ]]; then
        mutex-dbg "Removing old mutex"
        rm -rf $MUTEX_LOCK_FILE
      fi
    fi
    local time=$(( ${EPOCHSECONDS:-$(epochSeconds)} + $timeout ))
    local ct=0
    while [[ $ct -lt $time ]]; do
      if command mkdir $MUTEX_LOCK_FILE 1>/dev/null 2>&1; then
        mutex-dbg "Mutex locked"
        export MUTEX_CREATED=true
        return 0
      fi
      sleep "$(echo $RANDOM | awk '{print 0.2 + ( $1 % 10 ) / 15}')"
      ct=${EPOCHSECONDS:-$(epochSeconds)}
    done
    mutex-dbg "Mutex not locked"
    return 1
  } # }}}
  mutex-unlock() { # {{{
    mutex-dbg "Unlocking (created=$MUTEX_CREATED)"
    $MUTEX_CREATED && rm -rf $MUTEX_LOCK_FILE
    local err=$?
    mutex-dbg "Mutex unlocked ($err)"
    return $err
  } # }}}
  mutex-deinit() { # {{{
    mutex-dbg "De-initialization"
    export MUTEX_CREATED=false
    export MUTEX_LOCK_FILE=
    unset MUTEX_CREATED MUTEX_LOCK_FILE MUTEX_ACCESS_MIN_DELTA
    unset -f mutex-lock mutex-unlock mutex-deinit mutex-exit mutex-dbg
  } # }}}
  mutex-exit() { # {{{
    mutex-dbg "Exit trap"
    mutex-unlock
    mutex-deinit
    return 0
  } # }}}
  export -f mutex-lock mutex-unlock mutex-deinit mutex-exit
  export MUTEX_ACCESS_MIN_DELTA="$((10*60))"
  export MUTEX_CREATED=false
  export MUTEX_DBG=false
  local set_trap=true
  local clean_on_start=false
  [[ ! -e $LOCK_DIR ]] && command mkdir -p $LOCK_DIR >/dev/null
  shift
  while [[ ! -z $1 ]]; do
    case $1 in
    --auto-clean-after) export MUTEX_ACCESS_MIN_DELTA="${2:-60}"; shift;;
    --no-trap)          set_trap=false;;
    --clean-on-start)   clean_on_start=true;;
    --dbg)              MUTEX_DBG=true;;
    esac
    shift
  done
  mutex-dbg "Mutex initialized [$MUTEX_LOCK_FILE, clean=$clean_on_start, trap=$set_trap, delta=$MUTEX_ACCESS_MIN_DELTA)"
  $clean_on_start && rm -rf $MUTEX_LOCK_FILE
  $set_trap && trap 'mutex-exit' EXIT
} # }}}
export -f mutex-init

