#!/usr/bin/env bash
# vim: fdl=0

__open_common() { # {{{
  local i= openExt="__util_open"
  $IS_MAC && openExt="__util_open_osx"
  case $1 in
  @@) # {{{
    getFileList '*.enc'
    for i in $BASH_PROFILES_FULL; do
      [[ -e "$i/aliases" ]] && $i/aliases $openExt "@@"
    done;; # }}}
  *.enc) # {{{
    cmd="encryptor --edit $f"
    cmdParams= doDisown=false;; # }}}
  *) # {{{
    for i in $BASH_PROFILES_FULL; do
      [[ -e "$i/aliases" ]] && cmd="$($i/aliases $openExt "$f")" && return
    done
    return 1;; # }}}
  esac
}
export -f __open_common # }}}
if ! $IS_MAC; then
  open() { # @@ # {{{
    if [[ $1 == '@@' ]]; then # {{{
      case $3 in
      -d | --dir) # {{{
        echo "@@-d";; # }}}
      -f | --file)  # {{{
        __open_common @@
        getFileList '*.pcap'; getFileList '*.cap';; # }}}
      *) # {{{
        echo "-d --dir -f --file";; # }}}
      esac
      return 0
    fi # }}}
    local f= cmd= cmdParams=">/dev/null 2>&1 &" doDisown=true
    while [[ ! -z $1 ]]; do # {{{
      case $1 in
      -d | --dir)  f="$2";   shift;;
      -f | --file) f="$2";   shift;;
      *)           f="$1";   shift $#;;
      esac; shift
    done # }}}
    echorm -M -?
    case $f in
    '') # {{{
      cmd="nautilus .";; # }}}
    http://* | https://* | www.*) # {{{
      cmd="/opt/google/chrome/chrome \"$f\"" f=
      cmdParams="${cmdParams% &}" doDisown=false
      [[ ! -z $CHROME_MAIN_PROFILE ]] && cmd+=" --profile-directory='$CHROME_MAIN_PROFILE'";; # }}}
    *.pcap | *.cap) # {{{
      isInstalled wireshark || { echorm 0 "WireShark not installed"; return 1; }
      cmd="wireshark $f";; # }}}
    *) # {{{
      if ! __open_common "$f"; then
        if [[ -d $f ]]; then
          cmd="nautilus $f"
        else
          echorm 0 "Unknown action for $f"
          return 1
        fi
      fi;; # }}}
    esac
    (
      echorm "eval $cmd $cmdParams$($doDisown && echo " : ; disown")"
      eval "$cmd $cmdParams"
      $doDisown && disown
    )
  }
  COMPLETION_GENERIC_FUNCTIONS+=" open" # }}}
else
  open() { # @@ # {{{
    if [[ $1 == '@@' ]]; then # {{{
      case $3 in
      -f | --file)  # {{{
        __open_common @@
        getFileList '*.pcap'; getFileList '*.cap';; # }}}
      *) # {{{
        echo "-f --file";; # }}}
      esac
      return 0
    fi # }}}
    local f= cmd= cmdParams=">/dev/null 2>&1 &" doDisown=true
    while [[ ! -z $1 ]]; do # {{{
      case $1 in
      -f | --file) f="$2";   shift;;
      *)           f="$1";   shift $#;;
      esac; shift
    done # }}}
    echorm -M -?
    case $f in
    '') # {{{
      f=$PWD;; # }}}
    *) # {{{
      if ! __open_common "$f"; then
        if [[ -d $f ]]; then
          :
        else
          echorm 0 "Unknown action for $f"
          return 1
        fi
      fi;; # }}}
    esac
    if [[ -z $cmd ]]; then
      echorm "/usr/bin/open '$f'"
      /usr/bin/open "$f"
    else
      echorm "eval $cmd $cmdParams$($doDisown && echo " : ; disown")"
      eval "$cmd $cmdParams"
      $doDisown && disown
    fi
  } # }}}
fi
export -f __open_common open

