#!/usr/bin/env bash
# vim: fdl=0

output_to_file() { # @@ # {{{
  if [[ $1 == '@@' ]]; then
    echo "+tee=true +tee=false --ignore=err +fzf +-fzf --no-err --no-sort"
    return 0
  fi
  local use_tee=true
  local ignoreErr=false
  local colors= sort_params= errout="/dev/stderr"
  local use_fzf= fzf_params="--exit-0 --layout=reverse-list --no-sort --multi --height 100% --expect 'ctrl-p' --expect 'ctrl-s'"
  while [[ ! -z $1 ]]; do
    case $1 in
    true|false)   use_tee=$1;;
    +tee=*)       use_tee="${1/+tee=}";;
    --ignore-err) ignoreErr=true;;
    --sort-*)     sort_params+=" ${1#--sort-}";;
    --no-sort)    sort_params='NO-SORT';;
    --colors)     colors="--color=always";;
    --no-colors)  colors="--color=never";;
    +-fzf | +-f)  use_fzf=false;;
    +fzf  | +f)   use_fzf=$FZF_INSTALLED;;
    +fzf=*)       use_fzf=${1/+fzf=}; $use_fzf && use_fzf=$FZF_INSTALLED;;
    +fzf-p)       fzf_params+=" $2"; shift;;
    +fzf-*)       fzf_params+=" ${1#+fzf-}";;
    --no-err)     errout="/dev/null";;
    *)            cmd=$1; shift; break;;
    esac
    shift
  done
  [[ -z $sort_params ]] && sort_params="$OUTPUT_TO__SORT_PARAMS"
  [[ -z $cmd || $cmd == '-' ]] && cmd='cat -'
  if [[ -z $use_fzf ]]; then # {{{
    if [[ ! -t 1 ]]; then
      use_fzf=false
    else
      use_fzf="$(echo ",$FZF_USAGE," | command grep -o ',\s*OUTPUT-TO-FILE:[^,]\+,' | command grep -o 'true\|false')"
      [[ -z $use_fzf ]] && use_fzf=$FZF_INSTALLED
    fi
  fi # }}}
  local use_eval=
  if [[ $cmd == eval\ * ]]; then
    use_eval="eval "
    cmd=${cmd/eval }
  fi
  if $use_fzf; then
    case $cmd in
    ag* | ack* ) colors="--nocolor";;
    *grep*)      colors="--color=never";;
    esac
  fi
  local err= tmpFile=$TMP_MEM_PATH/otf-$$.tmp file="/dev/null"
  [[ ! -z $GREP_LAST_PATH && ! -e $GREP_LAST_PATH ]] && command mkdir -p $GREP_LAST_PATH
  if $use_tee; then # {{{
    if [[ ! -z $GREP_LAST_PATH ]]; then
      file="$GREP_LAST_PATH/last-$(date).txt"
      [[ -n $TMUX ]] && file="$GREP_LAST_PATH/$(tmux display-message -p -t $TMUX_PANE -F '#S-#I-#P')-$(date).txt"
    fi
    (
      echo "$cmd $@" | sed 's/--[^ ]*//g' | sed 's/  \+/ /g' | sed 's/ \+$//'
      echo "# "${PWD/$HOME/\~}
      echo "# "${file/$HOME/\~}
      echo "# sum"
      echo
    ) >$file
  fi # }}}
  ${DBG_SHOW_CMD:-false} && echor "$use_eval command $cmd $colors \"$@\""
  if $use_fzf; then # {{{
    $use_eval command $cmd $colors "$@" 2>$errout | { [[ $sort_params == 'NO-SORT' ]] && cat - || sort -st':' -k1,1 -k2,2n $sort_params; } >$tmpFile
    err=${PIPESTATUS[0]}
    if [[ $err == 0 ]]; then
      local res="$(cat $tmpFile | { $use_tee && tee -a $file || cat -; }  | { eval fzf $fzf_params; })"
      local key="$(echo "$res" | sed -n 1p)"
      res="$(echo "$res" | sed  1d)"
      case $key in
      ctrl-p) cat $tmpFile;;
      ctrl-s) [[ ! -z $res ]] && echo "$res" | xc; [[ ! -t 1 ]] && echo "$res";;
      '')     [[ ! -z $res ]] && echo "$res";;
      esac
    fi # }}}
  else # {{{
    $use_eval command $cmd $colors "$@" 2>$errout \
    | { [[ $sort_params == 'NO-SORT' ]] && cat - || sort -st':' -k1,1 -k2,2n $sort_params; } \
    | { $use_tee && tee -a $file || cat -; }
    err=${PIPESTATUS[0]}
  fi # }}}
  if $use_tee; then # {{{
    if [[ ! -z $GREP_LAST_PATH ]] && ( [[ $err == 0 ]] || $ignoreErr ) && [[ -e $tmpFile ]]; then
      local sum="$(cat $tmpFile | sort | sha1sum | cut -d' ' -f1)" i= found=false
      for i in $(find $GREP_LAST_PATH -type f | sort); do
        [[ "$(sed -n '4{p;q}' $i)" == "# sum: $sum" ]] && rm $file && file=$i && found=true && break
      done
      if ! $found; then
        sed -i -e '4s/.*/# sum: '"$sum"'/' -e "s/\x1B\[[0-9;]*[mGK]//g" $file
        if [[ -n $TMUX ]]; then
          ln -sf $file $GREP_LAST_PATH/$(tmux display-message -p -t $TMUX_PANE -F '#S-#I-#P')
          ln -sf $file $GREP_LAST_PATH/$(tmux display-message -p -t $TMUX_PANE -F '#S-#I')
          ln -sf $file $GREP_LAST_PATH/$TMUX_SESSION
        fi
        ln -sf $file $GREP_LAST_PATH/last
      fi
    else
      rm $file
    fi
  fi # }}}
  rm -f $tmpFile
  return $err
} # }}}
last_grep() { # @@ # {{{
  [[ -z $GREP_LAST_PATH ]] && return 1
  if [[ $1 == '@@' ]]; then # {{{
    if [[ $2 == 1 ]]; then
      local ret="+fzf -L -l -a -s -w -p --clean -f --file -F --follow"
      [[ -n $TMUX ]] && ret+=" $(command cd $GREP_LAST_PATH; ls ${TMUX_SESSION}-* 2>/dev/null | command grep -v '.txt')"
      echo $ret
    else
      case $3 in
      -a) echo "$(command cd $GREP_LAST_PATH; ls *.txt 2>/dev/null )";;
      -L) echo "$(command cd $GREP_LAST_PATH; ls 2>/dev/null | grep -v ".txt\|last" | sed -e 's/\(-[0-9]\{,2\}\)\{1,2\}$//' | sort -u)";;
      esac
      if [[ -n $TMUX ]]; then
        case $3 in
        -p) echo "$(command cd $GREP_LAST_PATH; ls $(tmux display-message -p -t $TMUX_PANE -F '#S-#I-#P')-* 2>/dev/null | command grep -v '.txt')";;
        -w) echo "$(command cd $GREP_LAST_PATH; ls $(tmux display-message -p -t $TMUX_PANE -F '#S-#I')-*    2>/dev/null | command grep -v '.txt')";;
        -s) echo "$(command cd $GREP_LAST_PATH; ls ${TMUX_SESSION}-*       2>/dev/null | command grep -v '.txt')";;
        esac
      fi
    fi
    return 0
  fi # }}}
  local f=
  local clean=false
  local show_file=false
  local show_greps=false
  local follow_link=false
  local use_fzf="$(echo ",$FZF_USAGE," | command grep -o ',\s*LAST-GREP:[^,]\+,' | command grep -o 'true\|false')"
  [[ -z $use_fzf ]] && use_fzf=$FZF_INSTALLED
  if [[ ! -z $1 ]]; then
    while [[ ! -z $1 ]]; do
      case $1 in
        -l) f=last;;
        -p) if [[ -n $TMUX ]]; then [[ -z $2 ]] && f=$(tmux display-message -p -t $TMUX_PANE -F '#S-#I-#P') || { f=$2; shift; }; fi;;
        -w) if [[ -n $TMUX ]]; then [[ -z $2 ]] && f=$(tmux display-message -p -t $TMUX_PANE -F '#S-#I')    || { f=$2; shift; }; fi;;
        -s) if [[ -n $TMUX ]]; then [[ -z $2 ]] && f=$TMUX_SESSION                         || { f=$2; shift; }; fi;;
        -L) if [[ -n $TMUX ]]; then [[ -z $2 ]] && f=$TMUX_SESSION                         || { f=$2; shift; }; fi; show_greps=true;;
        -f | --file)   show_file=true;;
        -F | --follow) follow_link=true;;
        +-fzf | +-f)   use_fzf=false;;
        +fzf  | +f)    use_fzf=$FZF_INSTALLED;;
        +fzf=*)        use_fzf=${1/+fzf=}; $use_fzf && use_fzf=$FZF_INSTALLED;;
        --clean)       clean=true;;
        -a)            ! $clean && { f=$2; shift;} || f=ALL;;
        *)             f=$1;;
      esac
      shift
    done
  else
    show_greps=true
    [[ -n $TMUX ]] && f="$TMUX_SESSION" || f=last
  fi
  if $show_greps; then
    local out=$TMP_MEM_PATH/grep-last-list-$f.txt
    rm -f $out
    for i in $(ls -t $GREP_LAST_PATH/${f}*.txt); do
      echo ${i/$HOME/\~}": $(head -n1 $i)" >>$out
    done
    if $use_fzf; then
      cat $out | fzf --prompt 'last-finds> ' --exit-0 --no-sort --no-multi --height 100%
    else
      vim --scratch -c 'setlocal conceallevel=2' $out
    fi
    return 0
  fi
  if $clean; then
    if [[ -z $f ]]; then
      f=last.txt
      [[ -n $TMUX ]] && f=$(tmux display-message -p -t $TMUX_PANE -F '#S-#I')
    elif [[ $f == ALL ]]; then
      f=
    fi
    rm -f $GREP_LAST_PATH/$f*
    return 0
  fi
  if [[ ! -z $f ]]; then
    f=$GREP_LAST_PATH/$f
    [[ ! -e $f ]] && return 1
    if $show_file; then
      [[ -h $f ]] && readlink $f || echo $f
      return 0
    fi
    if $use_fzf; then
      cat $($follow_link && echo $(readlink -f $f) || echo $f) | fzf --prompt 'last-finds> ' --exit-0 --no-sort --no-multi --height 100%
    else
      vim --scratch -c 'setlocal conceallevel=2' $($follow_link && echo $(readlink -f $f) || echo $f)
    fi
    return $?
  else
    local files=( $GREP_LAST_PATH/last.txt )
    [[ -n $TMUX ]] && files=( \
        $GREP_LAST_PATH/$(tmux display-message -p -t $TMUX_PANE -F '#S-#I-#P') \
        $GREP_LAST_PATH/$(tmux display-message -p -t $TMUX_PANE -F '#S-#I') \
        $GREP_LAST_PATH/$TMUX_SESSION \
        $GREP_LAST_PATH/last \
      )
    for f in ${files[*]}; do
      if [[ -e $f ]]; then
        if $show_file; then
          [[ -h $f ]] && readlink $f || echo $f
          return 0
        fi
        if $use_fzf; then
          cat $($follow_link && echo $(readlink -f $f) || echo $f) | fzf --prompt 'last-finds> ' --exit-0 --no-sort --no-multi --height 100%
        else
          vim --scratch -c 'setlocal conceallevel=2' $($follow_link && echo $(readlink -f $f) || echo $f)
        fi
        return $?
      fi
    done
  fi
  return 1
} # }}}

alias of='output_to_file' # @@
alias l-grep='last_grep' # @@
alias lgr='last_grep' # @@
