#!/usr/bin/env bash
# vim: fdl=0

PS1_envUpdater() { # {{{
  local list="$(command cd $BASHRC_RUNTIME_PATH; set +f; find . -maxdepth 1 -type f -name 'aliases-*.dump' -not -name '*-local.dump')" i= t= ts=
  for i in $list; do
    local t=${i#./aliases-} && t=${t%.dump} && t=${t//-/_}
    local -n tsRef=ALIASES_TS_${t^^}
    local ts="$(command stat -c %Y "$BASHRC_RUNTIME_PATH/$i")"
    ${PS1_DEBUG:-false} && echor "name: ALIASES_TS_${t^^}: ts:$ts ts-ref:$tsRef"
    if [[ $ts -gt ${tsRef:-0} ]]; then
      source "$BASHRC_RUNTIME_PATH/$i"
      tsRef=$ts
    fi
  done
} # }}}
__ps1_load_defaults() { # {{{
  export PS1_CFG_LINES=${PS1_CFG_LINES:-12}
  export PS1_CFG_LINES_FOR_SPLIT=${PS1_CFG_LINES_FOR_SPLIT:-8}
  export PS1_CFG_WIDTH=${PS1_CFG_WIDTH:-45}
  export PS1_COLUMNS_MARGIN=${PS1_COLUMNS_MARGIN:-40}
  export PS1_COLOR_OFF="${PS1_COLOR_OFF:-$(echo "\[$COff\]")}"
  export PS1_COLOR_ERR_0="${PS1_COLOR_ERR_0:-$(echo "\[$CIYellow\]")}"
  export PS1_COLOR_ERR_ERR="${PS1_COLOR_ERR_ERR:-$(echo "\[$CIRed\]")}"
  export PS1_COLOR_ERR_HL="${PS1_COLOR_ERR_HL:-$(echo "\[$CIBlue\]")}"
  export PS1_COLOR_ERR_H_NO="${PS1_COLOR_ERR_H_NO:-$(echo "\[$CIPurple\]")}"
  export PS1_COLOR_USER="${PS1_COLOR_USER:-$(echo "\[$CGray\]")}"
  export PS1_COLOR_HOST="${PS1_COLOR_HOST:-$(echo "\[$CGold\]")}"
  export PS1_COLOR_PWD="${PS1_COLOR_PWD:-$(echo "\[$CBlue\]")}"
  export PS1_COLOR_GIT="${PS1_COLOR_GIT:-$(echo "\[$CGray\]")}"
  export PS1_COLOR_JOBS="${PS1_COLOR_JOBS:-$(echo "\[$CIRed\]")}"
  export PS1_COLOR_JOBS_R="${PS1_COLOR_JOBS_R:-$(echo "\[$CIGreen\]")}"
  export PS1_COLOR_JOBS_S="${PS1_COLOR_JOBS_S:-$(echo "\[$CGold\]")}"
  export PS1_COLOR_NL="${PS1_COLOR_NL:-$(echo "\[$CGray\]")}"
  if [[ -z $PS1_COLOR_CURSOR ]] && ${PS1_CURSORS_CUSTOM:-true}; then
    if [[ $PS1_CURSOR_COLOR != 'false' ]]; then
      export PS1_COLOR_CURSOR_C="${PS1_COLOR_CURSOR_C:-$(echo "\[\e]12;${PS1_CURSOR_COLOR:-#00afaf}\a\]")}" # Set color to blue (#005e5d)
      export PS1_COLOR_CURSOR+=${PS1_COLOR_CURSOR+:-$(echo "$PS1_COLOR_CURSOR_C")}
    fi
    if [[ $PS1_CURSORS_TYPE != 'false' ]]; then
      export PS1_COLOR_CURSOR_T="${PS1_COLOR_CURSOR_T:-$(echo "\[\e[${PS1_CURSORS_TYPE:-2} q\]")}" # Type(steady,blinking): block(1,2), underline(3,4), bar(5,6)
      export PS1_COLOR_CURSOR+=${PS1_COLOR_CURSOR:-$(echo "$PS1_COLOR_CURSOR_T")}
    fi
  else
    export PS1_COLOR_CURSOR=
  fi
} # }}}
PS1_getColor() { # {{{
  case $1 in
  err-*)    if [[ ${1/err-} == '0' ]]; then
              if [[ ! -z $BASH_PHISTORY_FILE && ! -z $HISTFILE && ( $HISTFILE == $HISTFILE_ORIG || $HISTFILE != *'/.history' ) ]]; then
                echo -en "$PS1_COLOR_ERR_0"
              elif [[ ! -z $HISTFILE && $HISTFILE != $HISTFILE_ORIG && $HISTFILE == *'/.history' ]]; then
                echo -en "$PS1_COLOR_ERR_HL"
              else
                echo -en "$PS1_COLOR_ERR_H_NO"
              fi
            else
              echo -en "$PS1_COLOR_ERR_ERR"
            fi;;
  user)     echo -en "$PS1_COLOR_USER";;
  host)     echo -en "$PS1_COLOR_HOST";;
  pwd)      echo -en "$PS1_COLOR_PWD";;
  git)      echo -en "$PS1_COLOR_GIT";;
  off)      echo -en "$PS1_COLOR_OFF";;
  jobs)     echo -en "$PS1_COLOR_JOBS";;
  j-r)      echo -en "$PS1_COLOR_JOBS_R";;
  j-s)      echo -en "$PS1_COLOR_JOBS_S";;
  new-line) echo -en "$PS1_COLOR_NL";;
  cursor)   echo -en "$PS1_COLOR_CURSOR";;
  *)        printf "%s" $(get-color $1);;
  esac
} # }}}
PS1_covertMode() { # {{{
  local mode=
  ${PS1_SHORTEN_PATH:-false} && mode='SHORTEN'
  case $1 in
  usuper_full)   mode+=' user';&
  super_full)    mode+=' env-switches host pwd jobs git';;
  default_ussh)  mode+=' user';&
  default_ssh)   mode+=' host';&
  default)       mode+=' env-switches pwd_tmux jobs git';;
  short)         mode+=' pwd_short jobs ';;
  short_git_ssh) mode+=' host';&
  short_git)     mode+=' env-switches pwd_short jobs git';;
  very_short)    mode+=' ';;
  *)             mode+=" $(eval printf "\$PS1_MODE_${1^^}")";;
  esac
  [[ "$PS1_ENV_MODE" != 'false' ]] && mode+=" ${PS1_ENV_MODE:-env-no-rec}"
  mode+=' split-line'
  mode+=' prompt'
  [[ $TERM_ORIG != 'linux' ]] && mode+=' cursor'
  echo "$mode"
} # }}}
PS1_adjustPath() { # {{{
  local p="$1"
  [[ $p == $HOME* ]] && p=${p/#$HOME/~}
  ! ${shorten_path:-false} && printf "$p" && return 0
  local tmp=${p%/*}
  local last=${p/$tmp\/}
  local res=
  [[ $p == /* ]] && res="/"
  if [[ $tmp != $p ]]; then
    local i=
    for i in ${tmp//\// }; do
      if [[ $i == '...' ]]; then
        res+="$i"
      else
        res+="${i:0:1}"
      fi
      res+="/"
    done
  fi
  res+="$last"
  printf "$res"
  return 0
} # }}}
PS1_colorFormat() { # {{{
  local updateDummy=true
  local -n var=$1; shift
  [[ $1 == '-' ]] && shift && updateDummy=false
  [[ ! -z $2 ]] && var+="$(PS1_getColor "$1")$2$cOff$3"
  $updateDummy && ps1_dummy+="$2$3"
} # }}}
PS1_setter() { # {{{
  BASH_LAST_ERR=$?
  declare BASH_LAST_CMD=$_
  set +xv
  if [[ -e "$PWD" ]] && ${PS1_CONVERTER_CHECK_INODE:-true}; then # {{{
    local ino="$(command ls -id "$PWD" 2>/dev/null)"
    if [[ "$PWD" == "$PS1_LAST_PWD" ]]; then
      if [[ -z "$ino" || "$ino" != "$PS1_LAST_PWD_INO" ]]; then
        local oPWD=$OLDPWD
        command cd "$PWD"
        OLDPWD="$oPWD"
        export PS1_LAST_PWD_INO="$(command ls -id "$PWD" 2>/dev/null)"
        echormf -f?- || echor "Directory has changed"
      fi
    else
      export PS1_LAST_PWD="$PWD"
      export PS1_LAST_PWD_INO="$ino"
    fi
  else
    unset PS1_LAST_PWD PS1_LAST_PWD_INO
  fi # }}}
  if ${PS1_RESET_ERROR:-false}; then # {{{
    if [[ "$BASH_LAST_CMD" == "$BASH_LAST_LAST_CMD" ]]; then
      if [[ "$BASH_LAST_ERR" == "$BASH_LAST_LAST_ERR" ]]; then
        BASH_LAST_ERR=0 BASH_LAST_ERR_CLEARED=true
      elif ${BASH_LAST_ERR_CLEARED:-false}; then
        BASH_LAST_ERR=0
      fi
    else
      BASH_LAST_ERR_CLEARED=false
      BASH_LAST_LAST_CMD="$BASH_LAST_CMD"
    fi
    BASH_LAST_LAST_ERR="$BASH_LAST_ERR"
  fi # }}}
  PS1=""
  ${PS1_CONVERTER_ADD_SEPARATOR:-false} && [[ $LINES -ge $PS1_CFG_LINES ]] && PS1="\n"
  [[ -z $PS1_COLOR_OFF ]] && __ps1_load_defaults
  [[ -z $PS1_CONVERTER_ADD_SEPARATOR ]] && PS1_CONVERTER_ADD_SEPARATOR=${PS1_CFG_ADD_SEPARATOR:-true}
  # ps $PPID | command grep mc >/dev/null 2>&1 && PS1="mc|"
  local shorten_path=false v= ps1_dummy= tt=
  local cOff="$(PS1_getColor 'off')"
  # ${PS1_PROFILER:-false} && time-measure -v ps1
  for v in $(PS1_covertMode "${PS1_STATUS/:*}"); do
    # ${PS1_PROFILER:-false} && time-measure -v ps1 --reset
    tt=${EPOCHREALTIME/[,.]}
    while true; do case $v in
    SHORTEN) # {{{
      shorten_path=true;; # }}}
    user) # {{{
      PS1_colorFormat PS1 'user' "$USER" "@";; # }}}
    host) # {{{
      if [[ ! -z $PS1_CACHE_HOST_V ]];then # {{{
        PS1+="$PS1_CACHE_HOST_V"; ps1_dummy+="$PS1_CACHE_HOST_D"
        break
      fi # }}}
      local name=${PS1_HOSTNAME:-${HOSTNAME^^}} p=
      for p in $TMUX_REMOTE_PREFIXES; do
        name="${name/$p}"
      done
      export PS1_CACHE_HOST_D="${name^^}|"; export PS1_CACHE_HOST_V=
      PS1_colorFormat PS1_CACHE_HOST_V - 'host' "$name" "|"
      PS1+="$PS1_CACHE_HOST_V";; # }}}
    pwd) # {{{
      if [[ ! -e $PWD ]]; then # {{{
        if [[ $PWD == $PS1_CACHE_PWD ]]; then
          PS1+="$PS1_CACHE_PWD_V"; ps1_dummy+="$PS1_CACHE_PWD_D"
        else
          PS1+="${PWD##*/}"; ps1_dummy+="${PWD##*/}"
        fi
        PS1+="|"; ps1_dummy+="|"
        PS1_colorFormat PS1 err "ne"
        break
      fi # }}}
      if [[ $PWD == $PS1_CACHE_PWD && ! -z $PS1_CACHE_PWD_V ]]; then # {{{
        PS1+="$PS1_CACHE_PWD_V"; ps1_dummy+="$PS1_CACHE_PWD_D"
        break
      fi # }}}
      export PS1_CACHE_PWD="$PWD"
      local p=
      case $PWD in
      $HOME) p='~';;
      /)     p='/';;
      *)
        p=$(echo "${PWD/$HOME/\~}");
        local pp=${p%/*} pr=${p##*/}
        p="$(echo "$pp" | sed -E 's|/([^/]{3})[^/]*|/\1|g')/$pr";;
      esac
      export PS1_CACHE_PWD_D="$p"; export PS1_CACHE_PWD_V=
      PS1_colorFormat PS1_CACHE_PWD_V 'pwd' "$p"
      PS1+="$PS1_CACHE_PWD_V";; # }}}
    pwd_tmux) # {{{
      if [[ ! -e $PWD ]]; then # {{{
        if [[ $PWD == $PS1_CACHE_PWD ]]; then
          PS1+="$PS1_CACHE_PWD_V"; ps1_dummy+="$PS1_CACHE_PWD_D"
        else
          PS1+="${PWD##*/}"; ps1_dummy+="${PWD##*/}"
        fi
        PS1+="|"; ps1_dummy+="|"
        PS1_colorFormat PS1 err "ne"
        break
      fi # }}}
      if [[ $PWD == $PS1_CACHE_PWD ]]; then # {{{
        PS1+="$PS1_CACHE_PWD_V"; ps1_dummy+="$PS1_CACHE_PWD_D"
        break
      fi # }}}
      export PS1_CACHE_PWD="$PWD"
      local p=
      if [[ -n $TMUX ]]; then # {{{
        case $PWD in
        $HOME) p='~';;
        /)     p='/';;
        *)     local tmp="$PWD"
               local ps1_ignored=$PS1_IGNORED
               if [[ -z $ps1_ignored ]]; then
                 ps1_ignored="$(tmux show-options -v @tmux_path 2>/dev/null)"
                 [[ $ps1_ignored == $HOME || $ps1_ignored == '/' ]] && ps1_ignored=
               fi
               if [[ ! -z $ps1_ignored && $tmp == $ps1_ignored* ]]; then
                 tmp=".../${tmp/#$ps1_ignored/${ps1_ignored/*\/}}"
                 [[ $ps1_ignored == $HOME* ]] && tmp="~/$tmp"
               fi
               p="$(PS1_adjustPath "$tmp")";;
        esac
      else
        p=$(PS1_adjustPath "$PWD")
      fi # }}}
      export PS1_CACHE_PWD_D="$p"; export PS1_CACHE_PWD_V=
      PS1_colorFormat PS1_CACHE_PWD_V 'pwd' "$p"
      PS1+="$PS1_CACHE_PWD_V";; # }}}
    pwd_short) # {{{
      if [[ ! -e $PWD ]]; then # {{{
        if [[ $PWD == $PS1_CACHE_PWD ]]; then
          PS1+="$PS1_CACHE_PWD_V"; ps1_dummy+="$PS1_CACHE_PWD_D"
        else
          PS1+="${PWD##*/}"; ps1_dummy+="${PWD##*/}"
        fi
        PS1+="|"; ps1_dummy+="|"
        PS1_colorFormat PS1 err "ne"
        break
      fi # }}}
      if [[ $PWD == $PS1_CACHE_PWD ]]; then # {{{
        PS1+="$PS1_CACHE_PWD_V"; ps1_dummy+="$PS1_CACHE_PWD_D"
        break
      fi # }}}
      export PS1_CACHE_PWD="$PWD"
      local p=
      case $PWD in
      $HOME) p='~';;
      /)     p='/';;
      *)     p="${PWD/*\/}";;
      esac
      export PS1_CACHE_PWD_D="$p"; export PS1_CACHE_PWD_V=
      PS1_colorFormat PS1_CACHE_PWD_V 'pwd' "$p"
      PS1+="$PS1_CACHE_PWD_V";; # }}}
    jobs) # {{{
      [[ -e $PWD ]] || break
      ${PS1_CFG_ADD_JOBS:-true} || break
      if [[ ! -z $(jobs -p) ]]; then
        sleep 0.05
        local jobs_r=$(jobs -rp) jobs_s=$(jobs -sp) cnt=
        if [[ ! -z $jobs_r || ! -z $jobs_s ]]; then
          PS1_colorFormat PS1 'jobs' "["
          if [[ ! -z $jobs_r ]]; then
            cnt="$(echo "$jobs_r" | wc -l | xargs)"
            PS1_colorFormat PS1 'j-r' "$cnt"
          fi
          if [[ ! -z $jobs_s ]]; then
            cnt="$(echo "$jobs_s" | wc -l | xargs)"
            [[ ! -z $jobs_r ]] && PS1_colorFormat PS1 'jobs' "/"
            PS1_colorFormat PS1 'j-s' "$cnt"
          fi
          PS1_colorFormat PS1 'jobs' "]"
        fi
      fi;; # }}}
    git) # {{{
      [[ -e $PWD ]] || break
      if [[ -z $PS1_CFG_ADD_GIT ]]; then
        ${TMUX_STATUS_RIGHT_GIT_STATUS:-true} && [[ -n $TMUX ]] && break
      else
        $PS1_CFG_ADD_GIT || break
      fi
      local l= statF=$MEM_KEEP/tmux-git
      if ${PS1_CFG_GIT_USE_CACHE:-false} && [[ -e $statF ]]; then
        l=$(source "$statF"; echo "${git_stat[$PWD]}")
      else
        l="$(unset GIT_PS1_SHOWCOLORHINTS; __git_ps1 "%s")"
      fi
      [[ -z $l ]] && break
      PS1_colorFormat PS1 'git' "($l)";; # }}}
    split-line) # {{{
      [[ ${#ps1_dummy} -ge 4 ]] || break
      if ( ( ${PS1_CFG_ADD_SPLIT:-true} && [[ $LINES -ge $PS1_CFG_LINES_FOR_SPLIT ]] ) || [[ ${#ps1_dummy} -gt $PS1_CFG_WIDTH || ${#ps1_dummy} -gt $((COLUMNS - PS1_COLUMNS_MARGIN)) ]] ); then
        if [[ -z $PS1_CONVERTER_NEW_LINE ]]; then
          export PS1_CONVERTER_NEW_LINE=
          PS1_colorFormat PS1_CONVERTER_NEW_LINE - 'new-line' "$(get-unicode-char "new-line")"
        fi
        PS1+="\n$PS1_CONVERTER_NEW_LINE "
      fi;; # }}}
    prompt) # {{{
      local sign='\$'
      # ${PS1_DEBUG:-false} && set -xv
      if [[ ! -n $PS1_PSTREE_INSTALLED ]]; then
        export PS1_PSTREE_INSTALLED=true
        which pstree >/dev/null 2>&1 || PS1_PSTREE_INSTALLED=false
      fi
      if [[ ( ! -n $TMUX && $SHLVL -gt 1 ) || $SHLVL -gt 3 ]]; then
        local vv="PS1_SIGN_${$}"
        local v=${!vv}
        if [[ -z $v ]]; then
          local bashCnt=0
          if $PS1_PSTREE_INSTALLED; then
            local param="-a -s"
            $IS_MAC && param=
            local cmd="pstree $param -p $$ | sed -n --silent '1,/'$$'$/p'"
            if $IS_MAC; then
              cmd+=" | sed -n '/= \([0-9]\+\) .*bash$/s/.*= \([0-9]\+\) .*bash/\1/p'"
            else
              cmd+=" | sed -n '/bash,[0-9]\+$/s/.*,//p'"
            fi
            cmd+=" | xargs ps -f -p | command grep -c -e 'bash'"
            if ${PS1_DEBUG:-false} || ${PS1_DEBUG2:-false}; then
              echo "$cmd" >/dev/stderr
            fi
            bashCnt="$(eval $cmd)"
          else
            local p=$$ c=
            while true; do
              case "$(command ps -o cmd= $p)" in
              tmux\ *) break;;
              /bin/bash\ *) ;;
              *bash*)  bashCnt=$((bashCnt + 1));;
              esac
              p=$(echo $(command ps -o ppid= $p)) || break
              [[ $p == 1 || $p == 0 ]] && break
            done
          fi
          local forDocker=0
          $IS_DOCKER && forDocker=1
          bashCnt=$((bashCnt - forDocker - ${PS1_EXTRA_BASH:-0}))
          if [[ $bashCnt -gt 1 ]]; then
            v='@'
            if ${BASH_USE_UNICODE_FOR_NESTED_BASH:-true}; then
              v="${UNICODE_EXTRA_CHARS[nested_bash]}" a=$((bashCnt - 1))
              [[ $a -gt 20 ]] && a=20
              v="$(printf "%d" "'$v")"
              v="$(printf "\U$(printf '%08x' "$((v+a-1))")")"
            else
              [[ $((bashCnt - 1)) -gt 1 ]] && v+=$((bashCnt - 1))
            fi
            sign="$v"
          fi
          eval export PS1_SIGN_${$}=$sign
        else
          sign=$v
        fi
      fi
      # ${PS1_DEBUG:-false} && set +xv
      PS1_colorFormat PS1 - "err-$BASH_LAST_ERR" "$sign" " ";; # }}}
    cursor) # {{{
      PS1+="$(PS1_getColor 'cursor')";; # }}}
    env-switches) # {{{
      if [[ ! -z $VIRTUAL_ENV ]]; then
        [[ -z $PS1_CONVERTER_ENV_VENV ]] && export PS1_CONVERTER_ENV_VENV="$(get-unicode-char 'snake')"
        PS1+="$PS1_CONVERTER_ENV_VENV "; ps1_dummy+=".."
      fi;; # }}}
    env | env-no-rec) # {{{
      if [[ -e "$PWD" && "$PS1_ENV_PWD" != "$PWD" ]]; then
        cd_go_up() { # {{{
          local p="$1"
          [[ -z $p || ! -d $p ]] && return 0
          [[ $p != "$PS1_ENV_PWD" && $p == $HOME/* && $v == 'env' ]] && cd_go_up "${p%/*}"
          [[ -e "$p/.env-setup.sh" ]] && source "$p/.env-setup.sh"
          [[ -e "$p/.env" ]] && source "$p/.env"
        } # }}}
        cd_go_up "$PWD"
        unset cd_go_up
        if [[ ${PS1_HIST_CHANGE_TO_LOCAL:-true} && $HISTFILE == $HISTFILE_ORIG && -e $PWD/.history ]]; then # {{{
          [[ -z $BASH_ORIG_HISTFILE ]] && export BASH_ORIG_HISTFILE="$HISTFILE"
          export HISTFILE="$PWD/.history"
        fi # }}}
        export PS1_ENV_PWD="$PWD"
      fi;; # }}}
    *) # {{{
      PS1+="$(eval printf "\$$v")";; # }}}
    esac; break; done
    tt=$((${EPOCHREALTIME/[,.]} - $tt))
    ${PS1_PROFILER:-false} && echo "step: $v: $tt" >/dev/stderr
    # ${PS1_PROFILER:-false} && time-measure -v ps1 --msg "step: $v"
  done
  PS1+="$cOff"
  # ${PS1_PROFILER:-false} && time-measure -v ps1 --end
  export PS1
} # }}}
ps1_toggle() { # @@ # {{{
  local i=
  local fullName=, shortName=
  local oldIFS=$IFS
  if [[ $1 == '@@' ]]; then # {{{
    local ret="next"
    ret+=" hl hn hr ht $(echo hist-{local,no,no-pers,restore,stat})"
    ret+=" split nl gt"
    for i in ${PS1_MODES[*]}; do
      IFS=':' read fullName shortName <<<"$i"
      ret+=" $fullName"
    done
    echo "$ret"
    IFS=$oldIFS
    return 0
  fi # }}}
  # Toggles # {{{
  case $1 in
  split) # {{{
    ${PS1_CFG_ADD_SPLIT:-true} && export PS1_CFG_ADD_SPLIT=false || export PS1_CFG_ADD_SPLIT=true
    return 0;; # }}}
  nl) # {{{
    $PS1_CONVERTER_ADD_SEPARATOR && export PS1_CONVERTER_ADD_SEPARATOR=false || export PS1_CONVERTER_ADD_SEPARATOR=true
    return 0;; # }}}
  gt) # {{{
    if [[ -z $PS1_CFG_ADD_GIT ]]; then
      if ${TMUX_STATUS_RIGHT_GIT_STATUS:-true} && [[ -n $TMUX ]]; then
        export PS1_CFG_ADD_GIT=false
      else
        export PS1_CFG_ADD_GIT=true
      fi
    else
      $PS1_CFG_ADD_GIT && export PS1_CFG_ADD_GIT=false || export PS1_CFG_ADD_GIT=true
    fi
    return 0;; # }}}
  hist-local | hist-no | hist-no-pers | hist-restore | hist-stat | hl | hn | ht | hr) # {{{
    local cmd="$1"
    if [[ "$cmd" == 'ht' ]]; then
      [[ ! -z $BASH_PHISTORY_FILE ]] && cmd='hn' || cmd='hr'
    fi
    case $cmd in
    hist-local | hl) # {{{
      [[ -z $BASH_ORIG_PHISTORY_FILE ]] && export BASH_ORIG_PHISTORY_FILE="$BASH_PHISTORY_FILE"
      [[ -z $BASH_ORIG_HISTFILE ]] && export BASH_ORIG_HISTFILE="$HISTFILE"
      [[ -z $BASH_ORIG_HISTIGNORE ]] && export BASH_ORIG_HISTIGNORE="$HISTIGNORE"
      unset BASH_PHISTORY_FILE
      export HISTFILE="$PWD/.history"
      [[ -e $PWD/.history.ign && ! -e $PWD/.history ]] && export HISTFILE="$PWD/.history.ign";; # }}}
    hist-no | hn) # {{{
      [[ -z $BASH_ORIG_PHISTORY_FILE ]] && export BASH_ORIG_PHISTORY_FILE="$BASH_PHISTORY_FILE"
      [[ -z $BASH_ORIG_HISTFILE ]] && export BASH_ORIG_HISTFILE="$HISTFILE"
      [[ -z $BASH_ORIG_HISTIGNORE ]] && export BASH_ORIG_HISTIGNORE="$HISTIGNORE"
      unset BASH_PHISTORY_FILE HISTFILE HISTIGNORE;; # }}}
    hist-no-pers) # {{{
      [[ -z $BASH_ORIG_PHISTORY_FILE ]] && export BASH_ORIG_PHISTORY_FILE="$BASH_PHISTORY_FILE"
      unset BASH_PHISTORY_FILE;; # }}}
    hist-restore | hr) # {{{
      [[ ! -z $BASH_ORIG_PHISTORY_FILE ]] && export BASH_PHISTORY_FILE="$BASH_ORIG_PHISTORY_FILE"
      [[ ! -z $BASH_ORIG_HISTFILE ]] && export HISTFILE="$BASH_ORIG_HISTFILE"
      [[ ! -z $BASH_ORIG_HISTIGNORE ]] && export HISTIGNORE="$BASH_ORIG_HISTIGNORE"
      unset BASH_ORIG_PHISTORY_FILE BASH_ORIG_HISTFILE BASH_ORIG_HISTIGNORE;; # }}}
    esac
    history -r
    [[ ${#cmd} == 2 ]] && return 0
    echo "ph=[$BASH_PHISTORY_FILE]" >/dev/stderr
    echo "hi=[$HISTFILE]" >/dev/stderr
    return 0;; # }}}
  esac # }}}
  local current=
  local next=
  IFS=':' read current next <<<"$PS1_STATUS"
  if [[ ! -z $1 ]]; then # {{{
    next=
    if [[ $1 == 'next' ]]; then
      next="next"
    else
      for i in ${PS1_MODES[*]}; do
        IFS=':' read fullName shortName <<<"$i"
        [[ $1 == $fullName || $1 == $shortName ]] && next="$fullName" && break
      done
    fi
    IFS=$oldIFS
    [[ -z $next ]] && return 1
    [[ $next == $current ]] && return 0
  fi # }}}
  if [[ $next == 'next' ]]; then # {{{
    for i in ${!PS1_MODES[*]}; do
      IFS=':' read fullName shortName <<<"${PS1_MODES[$i]}"
      if [[ $current == $fullName ]]; then
        i=$(( ($i + 1) % ${#PS1_MODES[*]}))
        IFS=':' read fullName shortName <<<"${PS1_MODES[$i]}"
        next=$fullName
        break
      fi
    done
    echormf -C 0 "Changing PS1 to %yellow:{$next}"
  fi # }}}
  unset ${!PS1_CACHE_*}
  export PS1_STATUS="$next:$current"
  IFS=$oldIFS
} # }}}
ps1_fix() { # {{{
  local current=$PROMPT_COMMAND
  PROMPT_COMMAND=$PROMPT_COMMAND_ORIG
  [[ $current != PS1_setter* ]] && PROMPT_COMMAND+="; $current"
  export PROMPT_COMMAND
} # }}}

alias pt='ps1_toggle' # @@
alias gt='ps1_toggle gt'
alias pth='ps1_toggle ht'
export HISTIGNORE+=":pt:pth:gt"

