#!/usr/bin/env bash
# vim: fdl=0

set-title() { # @@ # {{{
  $ALIASES_SCRIPTS/set-title.sh "$@"
} # }}}
set-title-pane() { # {{{
  if ${SET_TITLE_PANE_FULL:-false}; then
    set-title "$@"
    return 0
  fi
  local force=false
  [[ $1 == '-f' ]] && force=true && shift
  if $force || [[ -n $TMUX ]] || ${SET_TITLE_PANE_NO_TMUX:-true}; then
    local title="$@"
    [[ -z $title ]] && title="${PWD/$HOME/\~}" && title="${title##*/}"
    printf ']2;%s\\' "$title" >/dev/stderr
  fi
} # }}}
export -f set-title set-title-pane

