#!/usr/bin/env bash
# vim: fdl=0

status-wait-for() { # @@ # {{{
  $ALIASES_SCRIPTS/status/status-wait-for.sh "$@"
} # }}}
status() { # @@ # {{{
  $ALIASES_SCRIPTS/status/status.sh "$@"
} # }}}
export -f status-wait-for status

