#!/usr/bin/env bash
# vim: fdl=0

tmux-progress() { # @@ # {{{
  [[ ! -n $TMUX ]] && return
  $HOME/.tmux.bash progress_bar "$@"
} # }}}
tmux-lock-toggle() { # {{{
  [[ ! -n $TMUX ]] && return
  $HOME/.tmux.bash lock_toggle --ssh $@
} # }}}
export -f tmux-progress tmux-lock-toggle

export PHISTORY_IGNORED_COMMANDS+=":tm:tmux-progress:tmux-lock-toggle"

