[[keyboard.bindings]]
action = "Paste"
key = "v"
mods = "Control|Shift"
[[keyboard.bindings]]
action = "Copy"
key = "c"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0105" # ą
key = "a"
mods = "Alt|Control"
[[keyboard.bindings]]
chars = "\u0104" # Ą
key = "a"
mods = "Alt|Control|Shift"
[[keyboard.bindings]]
chars = "\u0107" # ć
key = "c"
mods = "Alt|Control"
[[keyboard.bindings]]
chars = "\u0106" # Ć
key = "c"
mods = "Alt|Control|Shift"
[[keyboard.bindings]]
chars = "\u0119" # ę
key = "e"
mods = "Alt|Control"
[[keyboard.bindings]]
chars = "\u0118" # Ę
key = "e"
mods = "Alt|Control|Shift"
[[keyboard.bindings]]
chars = "\u0142" # ł
key = "l"
mods = "Alt|Control"
[[keyboard.bindings]]
chars = "\u0141" # Ł
key = "l"
mods = "Alt|Control|Shift"
[[keyboard.bindings]]
chars = "\u0144" # ń
key = "n"
mods = "Alt|Control"
[[keyboard.bindings]]
chars = "\u0143" # Ń
key = "n"
mods = "Alt|Control|Shift"
[[keyboard.bindings]]
chars = "\u00f3" # ó
key = "o"
mods = "Alt|Control"
[[keyboard.bindings]]
chars = "\u00d3" # Ó
key = "o"
mods = "Alt|Control|Shift"
[[keyboard.bindings]]
chars = "\u015b" # ś
key = "s"
mods = "Alt|Control"
[[keyboard.bindings]]
chars = "\u015a" # Ś
key = "s"
mods = "Alt|Control|Shift"
[[keyboard.bindings]]
chars = "\u017a" # ź
key = "x"
mods = "Alt|Control"
[[keyboard.bindings]]
chars = "\u0179" # Ź
key = "x"
mods = "Alt|Control|Shift"
[[keyboard.bindings]]
chars = "\u017c" # ż
key = "z"
mods = "Alt|Control"
[[keyboard.bindings]]
chars = "\u017b" # Ż
key = "z"
mods = "Alt|Control|Shift"

[[keyboard.bindings]]
chars = "\u2013" # –
key = "-"
mods = "Alt"
[[keyboard.bindings]]
chars = "\u2014" # —
key = "-"
mods = "Alt|Shift"
[[keyboard.bindings]]
chars = "\u2026" # …
key = ";"
mods = "Alt"

