[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x928374"
blue = "0x83A598"
cyan = "0x8EC07C"
green = "0xB8BB26"
magenta = "0xD3869B"
red = "0xFB4934"
white = "0xEBDBB2"
yellow = "0xFABD2F"

[colors.cursor]
cursor = "0x00b5b2"
text = "0xe0e0e0"

[colors.normal]
black = "0x101010"
# black = "0x0c0c12"
# black = "0x101222"
blue = "0x458588"
cyan = "0x689D6A"
green = "0x98971A"
magenta = "0xB16286"
red = "0xED655C"
white = "0xFBF1C7"
yellow = "0xD79921"

[colors.primary]
background = "0x121212"
foreground = "0xFBF1C7"

[env]
TERM = "alacritty"

[font.bold]
family = "Fira Mono"
style = "Bold"

[font.bold_italic]
family = "Fira Mono"
style = "Bold Italic"

[font.italic]
family = "Fira Mono"
style = "Italic"

[font.normal]
family = "Fira Mono"
style = "Regular"

[font]
size = 14

[window]
dynamic_padding = true
dynamic_title = true

