#!/usr/bin/env bash
# vim: fdl=0

time2s() { # @@ # {{{
  if [[ $1 == '@@' ]]; then # {{{
    local t="now 0:00 15:00 @${EPOCHSECONDS:-$(epochSeconds)} 5m2s @"
    case $3 in
    --out | -o) echo "s abs abs-s delta";;
    --now)      echo "- 15:00 15h";;
    -s)         echo "$t";;
    --to-hms)   echo "$t";;
    --to-HMS)   echo "--utc --no-utc";;
    -c) # {{{
      if type color-list >/dev/null >&1; then
        color-list
      else
        echo $COLORS_BASIC_LIST
      fi;; # }}}
    *) # {{{
      case ${4:-$3} in
      --diff) echo "$t";;
      *)
        echo "-s --diff --diff-HMS --is-hms --is-HMS --to-hms --to-HMS --now -o --out --hms-only -c --split"
        echo "$t 5m 1h2m3s";;
      esac;; # }}}
    esac
    return 0
  fi # }}}
  local colorP= color= coff=
  while [[ ! -z $1 ]]; do
    case $1 in
    -c) # {{{
      colorP=$2; shift
      color=$(get-color "$colorP")
      [[ ! -z $color ]] && coff=$COff;;# }}}
    -s) # {{{
      if time2s --is-hms $2; then
        time2s $([[ ! -z $colorP ]] && echo "-c $colorP") $2 -o s
      else
        echo "${color}$(command date '+%s' -d "${2:-now}")${coff}"
      fi
      return 0;; # }}}
    --diff-HMS) # {{{
      [[ -z $2 ]] && return 1
      local diff=$(time2s --diff $2 $3)
      time2s $([[ ! -z $colorP ]] && echo "-c $colorP") --to-HMS --utc $diff
      return 0;; # }}}
    --diff) # {{{
      local d1=$2
      local d2=$3
      [[ -z $d2 && ! -z $d1 ]] && d2=$d1 && d1="now"
      if [[ -z $d1 ]]; then
        d1="${EPOCHSECONDS:-$(epochSeconds)}"
      elif [[ $d1 == @* || $d1 =~ ^([0-9]{7,})$ ]]; then
        d1="${d1#@}"
      else
        d1="$(time2s -s "$d1")"
      fi
      if [[ -z $d2 ]]; then
        d2="$(time2s -s "today 0:00")"
      elif [[ $d2 == @* || $d2 =~ ^([0-9]{7,})$ ]]; then
        d2="${d2#@}"
      else
        d2="$(time2s -s "$d2")"
      fi
      echo "${color}$((d1-d2))${coff}"
      return 0;; # }}}
    --is-hms) # {{{
      [[ -n $2 ]] || return 1
      [[ $2 =~ ^([0-9]+h){0,1}([0-9]+m){0,1}([0-9]+s){0,1}$ ]]
      return $?;; # }}}
    --is-HMS) # {{{
      [[ -n $2 ]] || return 1
      [[ $2 =~ ^([0-9]+):([0-9]+)(:[0-9]+)?$ ]]
      return $?;; # }}}
    --split) # {{{
      if [[ $2 =~ ^([0-9]+h){0,1}([0-9]+m){0,1}([0-9]+s){0,1}$ ]]; then
        local h=${BASH_REMATCH[1]%h}
        local m=${BASH_REMATCH[2]%m}
        local s=${BASH_REMATCH[3]%s}
        printf "%d %d %d\n" "$((10#${h:-0}))" "$((10#${m:-0}))" "$((10#${s:-0}))"
        return
      elif [[ $2 =~ ^([0-9]+):([0-9]+)(:[0-9]+)?$ ]]; then
        local h=${BASH_REMATCH[1]}
        local m=${BASH_REMATCH[2]}
        local s=${BASH_REMATCH[3]#:}
        printf "%d %d %d\n" "$((10#${h:-0}))" "$((10#${m:-0}))" "$((10#${s:-0}))"
        return
      fi
      return 1;; # }}}
    --to-HMS) # {{{
      shift
      local dateP="--utc"
      case $1 in
      --utc)    dateP="--utc"; shift;;
      --no-utc) dateP=""; shift;;
      '')       dateP="";;
      esac
      local s=${1:-${EPOCHSECONDS:-$(epochSeconds)}} dir=
      [[ $s == -* ]] && dir='-' && s=${s#-}
      echo "${color}$dir$(command date +'%H:%M:%S' $dateP -d @$s)${coff}"
      return 0;; # }}}
    --to-hms) # {{{
      local s=$2 h= m= dir=
      [[ $s == *:* || $s == @* ]] && s=$(time2s --diff "$s")
      [[ $s == -* ]] && dir='-' && s=${s#-}
      h=$((s/3600)) && s=$((s-h*3600))
      m=$((s/60))   && s=$((s-m*60))
      [[ $h != 0 ]] && h="${h}h" || h=
      [[ $m != 0 ]] && m="${m}m" || m=
      [[ $s != 0 || ( -z $h && -z $m ) ]] && s="${s}s" || s=
      echo "${color}$dir$h$m$s${coff}"
      return 0;; # }}}
    *) break;;
    esac; shift
  done
  local ts= outForm= h= m= s= out= now=${EPOCHSECONDS:-$(epochSeconds)} dir=1 hms_is=false hms_only=false
  while [[ ! -z $1 ]]; do # {{{
    case $1 in
    @)          echo $now; return 0;;
    --out | -o) outForm=$2; shift;;
    --now)      [[ $2 != - ]] && now=${EPOCHSECONDS:-$(epochSeconds)}; shift;;
    --hms-only) hms_only=true;;
    *)          ts=$1; [[ $ts == -* ]] && dir=-1 && ts=${ts#-};;
    esac
    shift
  done # }}}
  [[ -z $ts ]] && ts='now' && [[ -z $outForm ]] && outForm='s'
  [[ -z $outForm ]] && outForm='abs'
  if [[ $ts =~ ^([0-9]+h){0,1}([0-9]+m){0,1}([0-9]+s){0,1}$ ]]; then # {{{
    h="${BASH_REMATCH[1]%h}" m="${BASH_REMATCH[2]%m}" s="${BASH_REMATCH[3]%s}"
    out="$((${h:-0}*60*60 + ${m:-0}*60 + ${s:-0}))"
    hms_is=true # }}}
  elif [[ $ts =~ ^([0-9]+)$ ]]; then # {{{
    if [[ $ts =~ ^([0-9]{7,})$ ]]; then
      now=$(time2s -s '0:00')
      out=$(time2s --diff "@$ts" "@$now")
    else
      out="$ts"
    fi # }}}
  elif [[ $ts =~ ^([0-9]{0,4})[.-]?([0-9]{0,2})[.-]?([0-9]{1,2})[\ -]([0-9]{1,2}):?([0-9]{0,2})(:?([0-9]{0,2}))$ ]]; then # {{{
    local aDate=( "${BASH_REMATCH[@]}" )
    local aYear="$(date +%Y)"
    if (( ${#aDate[1]} == 0 )); then
      aDate[1]="$aYear"
    elif(( ${#aDate[1]} == 2 )); then
      aDate[1]="${aYear:0:2}${m[1]}"
    fi
    if (( ${#aDate[2]} == 0 )); then
      aDate[2]="$(date +%m)"
    fi
    aDate[3]="$(printf "%02d" $((10#${aDate[3]})))"
    aDate[4]="$(printf "%02d" $((10#${aDate[4]})))"
    aDate[5]="$(printf "%02d" $((10#${aDate[5]:-0})))"
    if (( ${#aDate[7]} == 0 )); then
      aDate[7]="00"
    fi
    ts="${aDate[1]}-${aDate[2]}-${aDate[3]} ${aDate[4]}:${aDate[5]}:${aDate[7]}"
    now=0
    out=$(command date +%s -d "$ts") # }}}
  else # {{{
    now=$(time2s -s '0:00')
    out=$(time2s --diff "$ts" "@$now")
  fi # }}}
  $hms_only && ! $hms_is && return 0
  case $outForm in # {{{
  s)      echo "${color}$out${coff}";;
  abs)    echo "${color}$(command date +$TIME_FMT -d "@$((now+dir*out))")${coff}";;
  abs-s)  echo "${color}$(command date +%s        -d "@$((now+dir*out))")${coff}";;
  delta)  echo "${color}$(time2s --diff "@$((now+dir*out))" "now")${coff}";;
  *)      echo "Unknown output form [$outForm]" >/dev/stderr && return 1;;
  esac # }}}
} # }}}
time-measure() { # @@ # {{{
  local tNow="$(command date +"%s%N")"
  if [[ $1 == '@@' ]]; then # {{{
    case ${4:-$3} in
    --test) echo "-v 50 100 200";;
    --out)  echo "/dev/stderr /dev/stdout";;
    -v | --var \
      | -r | --reset | --end \
      | --add-unit | --round=* | -s \
      | --msg) echo "---";;
    -u) echo "s ms us ns";;
    *)
      echo "--test --get-time -v --var -r --reset --end --add-unit --round=0 --round=1 --round=3 --round=6 --round= --msg --on-init"
      echo "-s -u -p --plain --no-plain --out -0 --from-0 -0-abs --from-0-abs $(command date +%s%N) -?";;
    esac
    return 0
  fi # }}}
  local t0= tLast= unit=s round= addUnit=false msg= onInit=false silent=${TIME_MEASURE_SILENT} d= plain=${TIME_MEASURE_PLAIN:-} out=${TIME_MEASURE_OUT:-/dev/stderr} from0Abs=false from0=false
  local LC_NUMERIC=
  local tLastVariable=${TIME_MEASURE_VARIABLE:-time-measure-var}
  if [[ $1 == '--test' ]]; then # {{{
    shift
    $ALIASES_SCRIPTS/time-tools/time-measure-test.sh "$@"
    return 0
  fi # }}}
  while [[ ! -z $1 ]]; do # {{{
    case $1 in
    -v | --var) # {{{
      export TIME_MEASURE_VARIABLE="$2"
      tLastVariable=$TIME_MEASURE_VARIABLE
      shift;; # }}}
    -r | --reset) # {{{
      tName="$TIME_MEASURE_PREFIX${tLastVariable//-/_}"
      local -n ns_last=${tName}_ns_last ns_0=${tName}_ns_0 diff_s_last=${tName}_diff_s_last diff_s_0=${tName}_diff_s_0 accu_0=${tName}_accu_0
      ns_last= ns_0= diff_s_last= diff_s_0= accu_0=;; # }}}
    --end) # {{{
      tName="$TIME_MEASURE_PREFIX${tLastVariable//-/_}"
      unset TIME_MEASURE_VARIABLE ${tName}_ns_last ${tName}_ns_0 ${tName}_diff_s_last ${tName}_diff_s_0 ${tName}_accu_0
      return 0;; # }}}
    -\?) # {{{
      tName="$TIME_MEASURE_PREFIX${tLastVariable//-/_}"
      echo "TIME_MEASURE_VARIABLE=$TIME_MEASURE_VARIABLE" >/dev/stderr
      import-module vGet prefix-vars
      vGet --all $tName >/dev/stderr
      return 0;; # }}}
    --add-unit)   addUnit=true;;
    --round=*)    round=${1#--round=};;
    --msg)        msg="$2"; silent=false; shift;;
    --on-init)    onInit=true;;
    --out)        out=$2; shift;;
    -p | --plain) plain=true;;
    --no-plain)   plain=false;;
    -s)           silent=true;;
    -u)           unit="$2"; shift;;
    --get-time)   echo "$tNow"; return 0;;
    -0-abs | --from-0-abs) from0Abs=true;; # does not change counters
    -0     | --from-0)     from0=true;;    # does not change counters
    [0-9]*)       tLast="$1"; t0="$1";;
    esac; shift
  done # }}}
  tName="$TIME_MEASURE_PREFIX${tLastVariable//-/_}"
  local -n ns_last=${tName}_ns_last ns_0=${tName}_ns_0 diff_s_last=${tName}_diff_s_last diff_s_0=${tName}_diff_s_0 accu_0=${tName}_accu_0
  [[ -z $tLast ]] && tLast=$ns_last
  t0=$ns_0
  if [[ -z $tLast ]]; then # First run: just collect time # {{{
    [[ "$msg" == 'init' ]] && onInit=true
    if [[ ! -z $msg ]] && $onInit; then
      if [[ ( $out == '/dev/stdout' && ! -t 1 ) || ( $out == '/dev/stderr' && ! -t 2 ) ]]; then
        [[ -z $plain ]] && plain=true
      fi
      ! $addUnit && unit=
      if ! ${plain:-false}; then
        printf "%s: %0.03f%s\n" "${msg:-$tLastVariable}" "0" "$unit" >$out
      else
        printf "%0.03f%s\n" "0" "$unit">$out
      fi
    fi
    ns_last="$(command date +"%s%N")"
    ns_0=$ns_last
    accu_0=0
    return 0
  fi # }}}
  local tDiffLast=$(calc -qp -- "($tNow - $tLast - (${TIME_MEASURE_OVERHEAD:-0}))")
  local tDiff0=$(   calc -qp -- "($tNow - $t0    - (${TIME_MEASURE_OVERHEAD:-0}))")
  [[ $tDiffLast == -* ]] && tDiffLast=$(calc -qp -- "($tNow - $tLast)")
  [[ $tDiff0    == -* ]] && tDiff0=$(   calc -qp -- "($tNow - $t0)")
  if ! ${silent:-false}; then # {{{
    local tDiff=$tDiffLast
    $from0Abs && tDiff=$tDiff0
    $from0    && tDiff=$accu_0
    case $unit in # {{{
    s)   d=9; unit=s;  [[ -z $round ]] && round=3;;
    ms)  d=6; unit=ms; [[ -z $round ]] && round=0;;
    us)  d=3; unit=us; [[ -z $round ]] && round=0;;
    ns)  d=0; unit=ns; [[ -z $round ]] && round=0;;
    *)   d=0; unit=ns; [[ -z $round ]] && round=0;;
    esac # }}}
    tDiff=$(calc -qp -- "($tDiff/(10^$d))")
    ! $addUnit && unit=
    LC_NUMERIC=C
    if [[ ( $out == '/dev/stdout' && ! -t 1 ) || ( $out == '/dev/stderr' && ! -t 2 ) ]]; then
      [[ -z $plain ]] && plain=true
    fi
    if ! ${plain:-false}; then
      printf "%s: %0.0${round}f%s\n" "${msg:-$tLastVariable}" "$tDiff" "$unit" >$out
    else
      printf "%0.0${round}f%s\n" "$tDiff" "$unit">$out
    fi
  fi # }}}
  if $from0 || $from0Abs; then return 0; fi
  diff_s_last=$(calc -qp -- "($tDiffLast / 1000000000)")
  diff_s_0=$(   calc -qp -- "($tDiff0    / 1000000000)")
  accu_0=$(     calc -qp -- "($accu_0    + $tDiffLast)")
  ns_last="$(command date +"%s%N")"
  return 0
} # }}}
sleep-precise() { # @@ # {{{
  local var="SLEEP_PRECISE_$$" keep=false save=false printTime=false reset=false
  if [[ $1 == '@@' ]]; then # {{{
    case $3 in
    -s | -S) echo "SLEEP_PER_STEP - 1.0";;
    --steps-in-round) echo "10 30 60 120";;
    *) echo "-v --var -k --keep -r --reset -s --save -i --info --test -S --steps-in-round"
    esac
    return 0
  fi # }}}
  sleep-precise-test() { # {{{
    import-module echor
    eval export ECHOR_NAME_$$="sleep-test"
    sleep-test() { # {{{
      export SLEEP_PRECISE_MARGIN=$1
      local msg="${2:-Evaluation}"
      local t1= t2= tSum=0 cnt=10 diff=
      echor "$msg (SLEEP_PRECISE_MARGIN=$SLEEP_PRECISE_MARGIN)"
      for i in $(seq 1 $cnt); do # {{{
        t1=${EPOCHREALTIME//[.,]}
        sleep-precise -s
        sleep 0.5
        sleep-precise 1
        t2=${EPOCHREALTIME//[.,]}
        diff=$(( (t2 - t1) - 1000000 ))
        tSum=$((tSum + diff))
        echor "[$i] $diff"
      done # }}}
      local margin=$((SLEEP_PRECISE_MARGIN + tSum / cnt))
      echo "$margin"
    } # }}}
    local narrowN=0 margin=${SLEEP_PRECISE_MARGIN:-0}
    case $1 in # {{{
    -)  narrowN=0;;
    '') margin=0; narrowN=3;;
    *)  margin=$1;;
    esac # }}}
    for (( i=1; i<=narrowN; ++i )); do # {{{
      echor "narrowing $i/$narrowN with $margin"
      margin=$(sleep-test $margin)
    done # }}}
    margin=$(sleep-test $margin "Verification")
    echor "export SLEEP_PRECISE_MARGIN=$margin"
  } # }}}
  local stepsInRound=60
  while [[ ! -z $1 ]]; do # {{{
    case $1 in
    -v | --var)   var+="_$2"; shift;;
    -k | --keep)  keep=true;;
    -r | --reset) keep=false;;
    -s | --save)  save=true;;
    --steps-in-round) stepsInRound="$2"; shift;;
    -S)           save=true; reset=true;;
    -i | --info)  printTime=true;;
    --test) shift; sleep-precise-test "$@"; return 0;;
    *) break;;
    esac; shift
  done # }}}
  local rt=${EPOCHREALTIME/[,.]} s2us=1000000 sleepDefault=1.0
  [[ -z $rt ]] && rt=$(( $(command date +%s%N) / 1000 ))
  local -n v=$var vEnd=${var}_end vSteps=${var}_steps vStep=${var}_step vSleep=${var}_sleep
  if [[ -z $v || $v == 0 ]] || $save; then # {{{
    v=$rt
    if $save && [[ ! -z $1 ]]; then
      if [[ -z $vStep ]] || $reset; then
        local sleepPerStep=$1
        [[ $sleepPerStep == '-' ]] && sleepPerStep=$sleepDefault
        [[ $sleepPerStep == *.* ]] || sleepPerStep="$sleepPerStep.0"
        sleepPerStep=$(( ${sleepPerStep%.*} * s2us + ${sleepPerStep#*.} * s2us / 10 ))
        steps=$(( $stepsInRound * s2us / $sleepPerStep ))
        vSleep=$sleepPerStep vSteps=$steps vStep=0
        vEnd=$((rt + vSteps * vSleep))
      fi
    fi
    return 0
  fi # }}}
  local sTime=${1:-$sleepDefault} m=${SLEEP_PRECISE_MARGIN:-3000}
  if [[ ! -z $vStep ]]; then
    if (( vEnd > rt )); then
      sTime=$(( (vEnd - v)/(vSteps - vStep) ))
    else
      sTime=0
    fi
    (( ++vStep < vSteps )) || { vStep=0; vEnd=$((vEnd + vSteps * vSleep)); }
    keep=true
  else
    [[ $sTime == *.* ]] || sTime="$sTime.0"
    sTime=$(( ${sTime%.*} * s2us + ${sTime#*.} * s2us / 10 ))
  fi
  sTime=$(( sTime - (rt - v) - m ))
  if (( $sTime > 0 )); then # {{{
    local skip=false
    while (( ${#sTime} < 6 )); do sTime="0$sTime"; skip=true; done
    if $skip; then
      sTime="0.$sTime"
    elif [[ $sTime =~ ^(.*)([0-9]{6})$ ]]; then
      sTime="${BASH_REMATCH[1]:-0}.${BASH_REMATCH[2]}"
    fi
    if $printTime; then
      echo $sTime
    else
      sleep $sTime
    fi
  elif $printTime; then
    echo 0
  fi # }}}
  if $keep; then
    eval export $var=${EPOCHREALTIME/[,.]}
  else
    eval export $var=0
  fi
} # }}}
get-ts() { # @@ # {{{
  if [[ $1 == '@@' ]]; then # {{{
    case $3 in
    -o) # {{{
      echo s{,.{m,u,n}s} ms{,.{u,n}s} ns{,.us} us;; # }}}
    *) # {{{
      echo "-u --add-unit -p --precise -r --raw -o"
      echo "REF-TIME-then-NOW-TIME";; # }}}
    esac
    return 0
  fi # }}}
  local now="${EPOCHREALTIME/[,.]}"
  [[ ! -z $now ]] && now="${now}000"
  local unit='us' out= ref=0 addUnit=false skipSettingNow=false
  [[ -z $1 ]] && out='raw'
  while [[ ! -z $1 ]]; do # {{{
    case $1 in
    -u | --add-unit) addUnit=true;;
    -p | --precise)  unit='ns';;
    -r | --raw)      out='raw';;
    -o)              out=$2; shift;;
    -o=*)            out=${1#-o=};;
    *)               ref=$1; [[ ! -z $2 ]] && now=$2 && skipSettingNow=true; shift $#; break;;
    esac; shift
  done # }}}
  case $unit in # {{{
  us) [[ -z $now ]] && now=$(command date +%s%N);;
  ns) ( ! $skipSettingNow || [[ -z $now ]] ) && now=$(command date +%s%N);;
  esac # }}}
  local diff= div=1 fraction= unitS= digs=3 sign=1
  [[ $now != '-' && $now != 0 ]] && diff=$((now - ref)) || diff=$ref
  if [[ -z $out ]]; then
    [[ -t 1 ]] && out="$unit" || out='raw'
  fi
  case $out in # {{{
  raw)       echo "$diff"; return 0;;
  s  | s.*)  div=1000000000;;
  ms | ms.*) div=1000000;;
  us | us.*) div=1000;;
  ns)        div=1;;
  *)         echorm 0 "Unsupported output format: '$out'"; return 1;;
  esac # }}}
  case $out in # {{{
  s.3  | s.ms)  fraction=1000000; digs=3;;
  s.6  | s.us)  fraction=1000;    digs=6;;
  s.9  | s.ns)  fraction=1;       digs=9;;
  ms.3 | ms.us) fraction=1000     digs=3;;
  ms.6 | ms.ns) fraction=1;       digs=6;;
  us.3 | us.ms) fraction=1;       digs=3;;
  *.*)          echorm 0 "Unsupported output format: '$out'"; return 1;;
  esac # }}}
  $addUnit && unitS="${out%%.*}"
  if [[ -z $fraction ]]; then # {{{
    echo "$((diff / div))$unitS" # }}}
  else # {{{
    [[ $diff -lt 0 ]] && sign=-1
    printf "%d.%0${digs}d%s\n" "$((diff / div))" "$((sign * (diff / fraction) % (div / fraction)))" "$unitS"
  fi # }}}
} # }}}
__export_time-tools() { # {{{
  export -f time2s time-measure sleep-precise get-ts
  if type -f compl-add >/dev/null 2>&1; then
    compl-add time2s time-measure sleep-precise get-ts
  fi
}
export -f __export_time-tools # }}}
if [[ $0 == ${BASH_SOURCE[0]} ]]; then
  __export_time-tools
  "$@"
fi
