#!/usr/bin/env bash
# vim: fdl=0

compl-short() { # @@ # {{{
  if [[ $1 == '@@' ]]; then # {{{
    echo "-1 -? --item -i --list -l -t"
    return 0
  fi # }}}
  local i= tool="-" item= explain=false len=2 wtd='get-list' addShorts=false
  while [[ ! -z $1 ]]; do # {{{
    case $1 in
    -1)          len=1;;
    --shorts)    addShorts=true;;
    -t)          tool=$2; shift;;
    -\?)         wtd='get-list'; explain=true;;
    --list | -l) wtd='get-list';;
    --item | -i) wtd='get-item'; item=$2; shift;;
    --args)      wtd='convert-args'; shift; item=("${@@Q}"); shift $#; break;;
    *)           item=$1; break;;
    esac; shift
  done # }}}
  [[ -z $tool ]] && echoe -m compl-short "Tool not provided" return 1
  import-module echor
  echorv -M 2 wtd
  case $wtd in
  get-item)     [[ -z $item ]] && return 0;;
  convert-args) [[ -z $item ]] && return 0;;
  esac
  if [[ $tool == '-' ]]; then # {{{
    tool="${FUNCNAME[1]}"
    [[ -z $tool || $tool == bash || $tool == main ]] && tool="$0"
  fi # }}}
  echorv -M 1 tool
  local list="$(
    for i in $($tool @@ -- | tr ' ' '\n'); do
      [[ $i == --?* ]] || { echorm -m compl-short 3 "skip:[$i]"; continue; }
      echo "$(echo "$i" | sed -n 's/-\+\([a-z]\)[^-]*/\1/gp') $i"
    done | sort)"
  $addShorts && list="$(echo -e "$list\n$($tool @@ --shorts)")"
  echormf 2 "list-pre:[$(echo "$list" | tr '\n' ':')]"
  local sLast= s= f= toRemove= remove=false i=
  while read s f; do # {{{
    remove=false
    [[ $s == $sLast ]] && remove=true && echormf 3 "checking $s [$f]: the same [= $sLast]"
    [[ ${#s} -lt $len && $s =~ ^[a-z] ]] && remove=true && echormf 3 "checking $s [$f]: too short [< $len]"
    $remove && toRemove+="\|^$s " || echormf 3 "checking $s [$f]: ok"
    sLast=$s
  done < <(echo "$list") # }}}
  toRemove="${toRemove#\\|}"
  echormf -f? && echorv -M 2 toRemove
  [[ -z $toRemove ]] || list="$(echo "$list" | command grep -v "$toRemove")"
  echormf 1 "list-post:[$(echo "$list" | tr '\n' ':'))]"
  while read s f; do
    s=${s#!}
    case $wtd in
    get-item) # {{{
      [[ $s == $item ]] && item="$f" && break;; # }}}
    get-list) # {{{
      if $explain; then
        echo "$s : $f"
      else
        echo "$s"
      fi;; # }}}
    convert-args) # {{{
      local itemN=() cnt=0
      for i in "${item[@]}"; do
        i="${i#!}"
        [[ $i == $s || $i == "'$s'" ]] && i="$f"
        itemN[cnt]="$i"
        cnt=$((cnt+1))
      done
      item=$itemN
      ;; # }}}
    esac
  done < <(echo "$list")
  case $wtd in
  get-item)     echo "$item";;
  convert-args) echo "${item[@]}";;
  esac
} # }}}
__export_compl-short() { # {{{
  import-module echor
  export __MODULE_COMPL_SHORT=true
  export -f compl-short
  if type -f compl-add >/dev/null 2>&1; then
    compl-add compl-short
  fi
} # }}}
if [[ $0 == ${BASH_SOURCE[0]} ]]; then
  __export_compl-short
  "$@"
fi

