# general {
#     no_fade_in = false
#     grace = 0
#     disable_loading = true
# }

background {
    monitor =
    # path = /usr/share/sddm/themes/silent/backgrounds/smoky.jpg
    path = /usr/share/sddm/themes/silent/backgrounds/rei.png
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 1 # 0 disables blurring
    blur_size = 4
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# TIME
label {
    monitor =
    text = $TIME
    color = rgba(195, 198, 251, 1.0)
    font_size = 64
    font_family = Red Hat Display ExtraBold
    position = 150, 80
    halign = left
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgb(151515)
    inner_color = rgb(200, 200, 200)
    font_color = rgb(10, 10, 10)
    fade_on_empty = true
    placeholder_text =
    hide_input = false
    position = 150, -20
    halign = left
    valign = center
}
