configuration {
    kb-row-up: "Up,Control+k";
    kb-row-down: "Down,Control+j";
    kb-accept-entry: "Control+m,Return,KP_Enter";
    kb-remove-to-eol: "Control+Shift+e";
}

@theme "/usr/share/rofi/themes/Monokai.rasi"
