#!/usr/bin/env bash
# vim: fdl=0

# Configure # {{{
export BASH_ALIASES_FROM_CMD=false
if [[ "${BASH_SOURCE[0]}" == "$0" && ! -z $1 ]]; then # {{{
  export BASH_ALIASES_FROM_CMD=true
  if [[ $1 == '--clean' ]]; then # {{{
    shift
    rm -f $BASHRC_RUNTIME_PATH/aliases*
  fi # }}}
else
  if [[ $1 == '--clean' ]]; then
    shift
    rm -f $BASHRC_RUNTIME_PATH/aliases*
    RCSTUFF_ALIASES_INSTALLED=false
  fi
  if ${RCSTUFF_ALIASES_INSTALLED:-false}; then
    while [[ ! -z $1 ]]; do
      case $1 in
      --env) shift; __aliases_do_env=true;;
      --force | --clean) shift;;
      *) declare -f ___rcstuff_aliases_markup >/dev/null 2>&1 && unset BASH_ALIASES_FROM_CMD && return 0
      esac
      shift
    done
  fi
  export RCSTUFF_ALIASES_INSTALLED=true
  ___rcstuff_aliases_markup() { : ; }
  export -f ___rcstuff_aliases_markup
fi # }}}
install-function() { # START: install-function # {{{
  $BASH_ALIASES_FROM_CMD && return 0
  local doCheck=true
  [[ $1 == --force-yes ]] && doCheck=false && shift
  local tool="$1"
  local add_completion="$2"
  local add_completion_old="$3"
  ! $doCheck || [[ $toInstall == *\ $tool\ * ]] || return 1
  [[ ! -z $add_completion ]] && export COMPLETION_GENERIC_FUNCTIONS+=" ${add_completion//:/ }"
  [[ ! -z $add_completion_old ]] && export COMPLETION_GENERIC_FUNCTIONS_OLD+=" ${add_completion_old//:/ }"
  return 0
}
export -f install-function
# END: install-function # }}}
install-extensions() { # START: install-extensions # {{{
  local ask=true
  [[ $1 == --no-ask ]] && ask=false && shift
  local name="$2"
  local dumpFile="$BASHRC_RUNTIME_PATH/aliases-$name.dump" lockDir="$BASHRC_RUNTIME_PATH/.lock-$name.lock"
  $BASH_ALIASES_FROM_CMD && [[ ! -e "$dumpFile" ]] && dumpFile="${dumpFile%.dump}-local.dump"
  if [[ ! -e "$dumpFile" ]]; then # {{{
    local i= fi= wdir=$1
    if ! $BASH_ALIASES_FROM_CMD; then
      ( ii=0; while ! command mkdir "$lockDir" 2>/dev/null && [[ $ii -lt 6 ]]; do
          sleep 0.5; ii=$(($ii+1))
        done
      )
    fi
    local complOrig="$COMPLETION_GENERIC_FUNCTIONS" && COMPLETION_GENERIC_FUNCTIONS=""
    local complOldOrig="$COMPLETION_GENERIC_FUNCTIONS_OLD" && COMPLETION_GENERIC_FUNCTIONS_OLD=""
    for i in $(command cd $wdir; find . -maxdepth 1 -type f \( -name '*.ign' -prune -o -name '*~' -prune -o -print \) | sed 's|^\./||' | sort -n); do # {{{
      fi="$wdir/$i"
      local fcon_= ask_i=$ask complOld= complNew= arkup= fc_i=
      mapfile -t fcon < <(command sed -n -e 1p -e '/# @@\|# @-@\|# @@:new/p' $fi)
      [[ "${fcon[0]}" == "#!"* ]] || { echoe -f "Skipping file [$i] because of missing shebang"; continue; }
      [[ $i =~ ^[0-9]+\..* ]] && i="${i#*.}"
      [[ $i == -* ]] && ask_i=true && i=${i#-}
      for fc_i in ${!fcon[*]}; do
        if false; then :
        elif [[ ${fcon[$fc_i]} =~ ^\ *([a-zA-Z].*)\(\)\ *\{\ *#\ (@-@|@@:new) ]]; then # }
          complNew+=":${BASH_REMATCH[1]}"
        elif [[ ${fcon[$fc_i]} =~ ^\ *([a-zA-Z].*)\(\)\ *\{\ *#\ @@ ]]; then # }
          complOld+=":${BASH_REMATCH[1]}"
        elif [[ ${fcon[$fc_i]} =~ ^\ *alias\ *([a-zA-Z].*)=.*\ *#\ (@-@|@@:new) ]]; then
          complNew+=":${BASH_REMATCH[1]}"
        elif [[ ${fcon[$fc_i]} =~ ^\ *alias\ *([a-zA-Z].*)=.*\ *#\ @@ ]]; then
          complOld+=":${BASH_REMATCH[1]}"
        fi
      done
      if install-function $(! $ask_i && echo "--force-yes") "$i" "${complNew#:}" "${complOld#:}"; then # {{{
        # command grep -q "^# env:" "$fi" && eval "$(sed -n '/# env: /s/# env: \(.*\)/\1/p' "$fi")"
        if [[ ! -e "$dumpFile" ]]; then
          cat >"$dumpFile" <<-EOF
						#!/usr/bin/env bash
						# vim: fdl=0
						
					EOF
        fi
        {
          echo "#-#-# START: $fi # {{{"
          /bin/cat "$fi"
          sed -n '/^# env: /s/# env: \(.*\)/\1/p' "$fi"
          echo "#-#-# END: $fi # }}}"
        } >>"$dumpFile"
      fi # }}}
    done # }}}
    echo >>"$dumpFile"
    local complUpdated="$COMPLETION_GENERIC_FUNCTIONS" && export COMPLETION_GENERIC_FUNCTIONS="$complOrig"
    local complOldUpdated="$COMPLETION_GENERIC_FUNCTIONS_OLD" && export COMPLETION_GENERIC_FUNCTIONS_OLD="$complOldOrig"
    (
      echo "export COMPLETION_GENERIC_FUNCTIONS+=\" $complUpdated\""
      echo "export COMPLETION_GENERIC_FUNCTIONS_OLD+=\" $complOldUpdated\""
    ) | sed 's/\s\+/ /g' >>"$dumpFile"
    rm -rf "$lockDir"
  fi # }}}
  if [[ -e "$dumpFile" ]]; then # {{{
    if $BASH_ALIASES_FROM_CMD; then # {{{
      for i in $BASH_ALIASES_DUMMY; do
        eval "$i() { :; }; export -f $i"
      done
    fi # }}}
    source "$dumpFile"
  fi # }}}
  if [[ $dumpFile != *'-local.dump' ]]; then
    local name=${2//-/_}
    export ALIASES_TS_${name^^}="$(command stat -c %Y "$dumpFile")"
  fi
}
export -f install-extensions
# END: install-extensions # }}}
# Check ALIASES_MAP # {{{
toInstall=''
if [[ $ALIASES_MAP == 'NONE' ]]; then
  [[ "${BASH_SOURCE[0]}" == "$0" ]] && exit 0 || return 0
fi
if [[ ! -z $ALIASES_MAP ]]; then # {{{
  a_map=" $ALIASES_MAP "
  if [[ $a_map == *\ BASIC\ * ]]; then
    a_map="${a_map//' BASIC '/ }"
  fi
  for i in $a_map; do
    case $i in
    -*) toInstall="${toInstall// ${i#-} / }";;
    *)  toInstall+=" $i ";;
    esac
  done
  unset a_map
fi # }}}
toInstall=" $toInstall "
# echoe -m aliases "To alias: [$toInstall]"
# }}}
# }}}
# Functions # {{{
if ! ${BASH_ALIASES_FROM_CMD} || ! declare -F $1 >/dev/null 2>&1; then
  install-extensions --no-ask "$SCRIPT_PATH/bash/aliases.d" main
fi
# }}}
# MAIN # {{{
# Source profiles # {{{
if ! declare -F compl-add >/dev/null 2>&1; then
  source "$BASH_ESSENTIALS_PATH/completion.basic" ""
fi
for profi in $BASH_PROFILES_FULL; do
  [[ -e $profi/aliases ]] && source $profi/aliases ''
done # }}}
# Check if not sourced and called with params # {{{
if $BASH_ALIASES_FROM_CMD; then # {{{
  # ALIASES_SILENT=true
  ${ALIASES_SILENT:-true} || echoe -w "cmd=[$@]"
  cmd=$1 err=0
  shift
  case $cmd in
  --source) # {{{
    for i; do
      if declare -F $i >/dev/null 2>&1; then
        declare -f $i
      else
        err=1
      fi
    done;; # }}}
  *) # {{{
    $cmd "$@"
    err=$?;; # }}}
  esac
  exit $err # }}}
else # {{{
  case $1 in
  --source) # {{{
    shift
    for i; do
      if declare -F $i >/dev/null 2>&1; then
        declare -f $i
      fi
    done;; # }}}
  *) # {{{
    if ${__aliases_do_env:-false} && $IS_MAC; then
      while read __aliases_f; do
        type $__aliases_f | command grep -q ";&" && echo "Function '$__aliases_f() not exported'" >/dev/stderr && continue
        export -f $__aliases_f
      done < <(declare -F | command grep " -f [^_]" | awk '{print $3}')
      unset __aliases_f
    fi
    unset __aliases_do_env;; # }}}
  esac
fi # }}} # }}}
# }}}
# Cleaning # {{{
unset toInstall i BASH_ALIASES_FROM_CMD ALIASES_AUTO_SUDO_PROMPT
# }}}
