#!/usr/bin/env bash

[[ -f $HOME/.bashrc ]] || return
if [[ -e $HOME/.runtime/bashrc/bashrc.initialized && ( -z $SSH_CONNECTION || -n $TMUX ) ]]; then
  source $HOME/.bashrc --do-basic
else
  source $HOME/.bashrc --do-full
fi

