#!/usr/bin/env bash
# vim: fdl=0

# Is installed # {{{
${RCSTUFF_CFG_INSTALLED:-false} && [[ $1 != '--force' ]] && return 0
[[ $1 == '--force' ]] && shift
export RCSTUFF_CFG_INSTALLED=true
# }}}
# Exports # {{{
# Git # {{{
export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
export GIT_PS1_SHOWUPSTREAM="auto"
export GIT_PS1_DESCRIBE_STYLE="branch"
unset GIT_PS1_SHOWCOLORHINTS
export GIT_USER_DEFAULT="${PERS_NAME_LONG}:${PERS_EMAIL}"
export GIT_USER_123="${PERS_USER_SHORT}:${PERS_EMAIL_123}"
# }}}
# Ack # {{{
export ACK_OPTIONS="-k --smart-case --color-filename=cyan --color-lineno=green --color-match=yellow"
export ACK_PAGER="less"
export ACK_PAGER_COLOR="less"
# }}}
# Ag # {{{
export AG_OPTIONS="--color-path=38;5;6 --color-line-number=38;5;10 --color-match=38;5;214"
# }}}
# Bat # {{{
if [[ -z $BAT_INSTALLED ]]; then
  export BAT_INSTALLED=false
  if is-installed -w bat >/dev/null 2>&1; then
    BAT_INSTALLED=true
    export BAT_PRG="bat"
  elif is-installed -w batcat >/dev/null 2>&1; then
    BAT_INSTALLED=true
    export BAT_PRG="batcat"
  fi
  if $BAT_INSTALLED; then
    export BAT_THEM2="Solarized (dark)"
    export BAT_THEME="TwoDark"
    help() {
      "$@" --help 2>&1 | $BAT_PRG -p -l help --theme "$BAT_THEM2"
    }
  else
    help() {
      "$@" --help
    }
  fi
fi
# }}}
# FZF # {{{
if $FZF_INSTALLED && ( [[ -z $FZF_DEFAULT_COMMAND ]] || $RCSTUFF_FORCE ); then
  export FZF_DEFAULT_COMMAND="fzf-find"
  export FZF_ALT_C_COMMAND="fzf-find -d"
  fzf_exe="$ALIASES_SCRIPTS/fzf-tools/fzf-exe.sh" # has to be in this form for vim fzf-plugin
  if [[ -e $BASHRC_RUNTIME_PATH/fzf.def-opts.env ]]; then # {{{
    export FZF_DEFAULT_OPTS="$(cat $BASHRC_RUNTIME_PATH/fzf.def-opts.env)"
  else
    export FZF_DEFAULT_OPTS="$(cat <<-EOF
				--multi --exact --no-sort --exit-0 --algo=v2 --no-mouse --height 80% --border --tabstop=2
				--color=dark,fg:15,fg+:15,bg+:238,hl:214,hl+:208,marker:3,pointer:2
				--layout=reverse-list
				--preview '$fzf_exe -c prev --prev 10 -f {1}'
				--preview-window 'hidden'
				--bind 'f1:execute($fzf_exe -c less -f {1})'
				--bind 'f2:execute($fzf_exe -c vim  -f {1})'
				--bind 'f3:execute($fzf_exe -c pane -f {1})'
				--bind 'esc:cancel'
				--bind 'ctrl-a:select-all'
				--bind '?:toggle-preview'
				--bind 'ctrl-s:toggle-sort'
				--bind 'ctrl-y:preview-up'
				--bind 'ctrl-e:preview-down'
			EOF
    )"
    export FZF_DEFAULT_OPTS="$(echo $FZF_DEFAULT_OPTS | tr -s ' ')"
    echo "$FZF_DEFAULT_OPTS" >$BASHRC_RUNTIME_PATH/fzf.def-opts.env
  fi # }}}
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
  export FZF_CTRL_T_OPTS="--preview '$fzf_exe -c prev --prev 20 -f {1}'"
  export FZF_ALT_C_OPTS="-e -x --layout=reverse --prompt='> '"
  declare -A +x fzfUsageA=([ack-ag]=true [mg]=true [grep]=false [out2file]=true [last-grep]=false [phist]=true [cd]=true)
  export FZF_USAGE="$(declare -p fzfUsageA)"
  unset fzf_exe fdfindCmd fzfUsageA
elif ! $FZF_INSTALLED; then
  [[ ! -z "$PS1" ]] && echoe -s "FZF not found"
fi
# }}}
# Default values for functions and scripts # {{{
export GREP_DEFAULT_PARAMS="--color --binary-files=binary"
export GREP_COLORS='mt=38;5;214:ne:fn=36'
export HL_DEFAULTS+=" +cB@'\<TB\]'"
export HL_DEFAULTS+=" +cGold@'\<\(AA|BB|TT\)\>\( |$\)'"
export HL_DEFAULTS+=" +cRed@'\<\(EE|FF\)\>\( |$\)'"
export HL_DEFAULTS+=" +cGreen@'\<II\>\( |$\)'"
export HL_DEFAULTS+=" +cCyan@'\<IMP\>\( |$\)'"
export HL_DEFAULTS+=" +c'38;5;9' '# {{{|# }}}'"
export HL_DEFAULTS+=" +cGreen@'\<[a-z0-9]\{40\}\>'"
export RSYNC_DEFAULT_PARAMS_VERBOSE="-ahtpH --no-whole-file --modify-window=2 --progress"
export RSYNC_DEFAULT_PARAMS="$RSYNC_DEFAULT_PARAMS_VERBOSE --no-v --no-progress --info=progress2"
export RSYNC_DEFAULT_PARAMS_FAT="--update --times -rlptgoD --size-only --no-o --no-g --no-p -O"
export TMUX_INIT_SESSIONS+=" MAIN"
export TMUX_LOCK_TIMEOUT="$(( 20 * 60 ))"
export TMUX_PREFIX_2='C-q'
export TMUX_STATUS_LEFT_EXTRA_MAP+="MAIN:${UNICODE_EXTRA_CHARS[tmux-main]}\n"
export TMUX_STATUS_RIGHT_EXTRA+=" 001:tmux_info 002:cpu 003:net 005:ssh 008:reminder 010:weather 015:usb 025:time 035:progress_bar"
export TMUX_SWITCH_WINDOW_MAIN_MAP="*:@2"
[[ ! -z $TMUX_VERSION ]] || export TMUX_VERSION="$(type tmux >/dev/null 2>&1 && tmux -V | sed 's/\.//' | cut -c6-7)"
[[ -n "$SSH_CLIENT" ]] && export TMUX_LOCK_TIMEOUT="0"
export CD_LAST_DIRS=($PWD)
[[ -e $HOME/Downloads ]] && export CD_LAST_DIRS_STORED+=":Dw@$HOME/Downloads"
[[ -e $HOME/Desktop   ]] && export CD_LAST_DIRS_STORED+=":De@$HOME/Desktop"
export CD_LAST_DIRS_STORED+=":tmux@--cd-spec"
export CD_LAST_DIRS_STORED+=":docs@--cd-spec"
# }}}
# Editor # {{{
if [[ -z $EDITOR ]] || $RCSTUFF_FORCE; then
  export EDITOR="vim -c 'set cursorline'"
  [[ $(which vim 2>/dev/null) == "$HOME/"* ]] && export EDITOR="vim --fast -cl"
  export VISUAL=$EDITOR
  export SVN_EDITOR=$EDITOR
fi
# }}}
# }}}
# Shell setup # {{{
export QUOTING_STYLE='literal'
export HISTCONTROL="erasedups:ignoreboth"
export HISTFILESIZE=1000
export HISTFILE=$HOME/.bash_history
[[ -n $TMUX_SESSION ]] && export HISTFILE=$TMUX_SESSION_PATH/bash_history
export HISTFILE_ORIG=$HISTFILE
unset HISTTIMEFORMAT
[[ -z $BASH_PHISTORY_FILE ]] && export BASH_PHISTORY_FILE="$HOME/.bash_phistory"
if $BASHRC_FULL_START && [[ -e "$BASH_PHISTORY_FILE" ]]; then
  sed -i '/ | [0-9]\{8\}-[0-9]\{6\} | \.\.\.$/d' "$BASH_PHISTORY_FILE" 2>/dev/null
  sed -i '/^[^|]/d' "$BASH_PHISTORY_FILE" 2>/dev/null
fi
[[ -z $BASH_PHISTORY_SUM_CMD ]] && export BASH_PHISTORY_SUM_CMD="sha256sum | cut -d' ' -f1 |  xxd -r -p | base64"
shopt -s autocd
shopt -s cdspell
shopt -s checkwinsize
shopt -s cmdhist
shopt -s dirspell
shopt -s extglob
shopt -s globstar
shopt -s histappend
shopt -s histverify
shopt -s progcomp
shopt -s progcomp_alias
set +f
export GLOBIGNORE=.:..
# }}}
# InputRC: Bash shortcuts # {{{
goto_vi_command() { # {{{
  [[ $READLINE_POINT == ${#READLINE_LINE} && $READLINE_POINT -gt 0 && ${READLINE_LINE:$((READLINE_POINT-1)):1} != ' ' ]] && READLINE_LINE="$READLINE_LINE " && READLINE_POINT=$((READLINE_POINT+1))
  bind 'set keymap vi-command'
  return 0
} # }}}
if [[ ! -z $PS1 ]]; then
  bind 'set enable-bracketed-paste on'
  if [[ $BASH_VERSION == '4.4'* || $BASH_VERSION == '5'* ]]; then
    bind 'set colored-completion-prefix on'
    if [[ ! -z $INPUTRC_MODE_CHAR ]]; then
      bind 'set vi-ins-mode-string "\1\e[0;33m\2'"$INPUTRC_MODE_CHAR"'\1\e[0m\2"'
      bind 'set vi-cmd-mode-string "\1\e[0;34m\2'"$INPUTRC_MODE_CHAR"'\1\e[0m\2"'
      bind 'set emacs-mode-string  "\1\e[0;31m\2'"$INPUTRC_MODE_CHAR"'\1\e[0m\2"'
    fi
  fi
  for i in {emacs,vi-command,vi-insert}; do
    bind "set keymap $i"
    # bind -r '\C-k'    # k for utils
    bind -x '"\C-kj":    READLINE_LINE="# $(eval "$READLINE_LINE")";READLINE_POINT=${#READLINE_LINE}'
    pre=
    case $i in
    emacs)
      ;;
    vi-command) # vi-movement-mode
      pre='i'
      ;;
    vi-insert) # vi-editing-mode
      bind -x '"\C-kk": "history -r && echoe -c -m bash history reloaded"'
      bind    '"\C-kil": "\C-g logout\C-m"'
      bind    '"\C-kib": "\C-g byebye\C-m"'
      if $FZF_INSTALLED; then
        bind -x '"\C-f": "fzfwr iRC"'
        bind -x '"\C-p": "fzf-file-widget"'
        bind -x '"\C-x": "__env_fzf_autocomplete_inline__"'
      fi
      ;;
    esac
    bind    '"\C-k\C-d":  "'${pre}'\C-g exit 1\C-m"'
    bind    '"\C-k\C-e":  "'${pre}'\C-g exec bash\C-m"'
    bind -x '"\C-k\C-f":  "source ~/.bashrc --force && echoe -c -m bash resourced"'
    bind    '"\C-k\C-h":  "'${pre}'\C-g pt ht && clear\C-m"'
    bind    '"\C-k\C-r":  "'${pre}'\C-g reset\C-m"'
    bind    '"\C-l":      "'${pre}'\C-g clr\C-m"'
    bind -x '"\C-k\C-l":  "clr --hist"'
  done
  unset i pre
  bind 'set editing-mode vi'
  bind 'set keymap vi-insert'
fi
# }}}
# Completion # {{{
if [[ -f /etc/bash_completion ]] && ! shopt -oq posix && ! declare -F _completion_loader &>/dev/null; then
  source /etc/bash_completion
fi

if [[ -e $GIT_PATH ]]; then
  for i in $(ls $GIT_PATH/share/contrib/completion/{git-completion.bash,git-prompt.sh}); do
    [[ -f $i ]] && source $i
  done
fi
if ! declare -F __git_ps1 &>/dev/null; then
  $BASHRC_DBG && echoe -s "Using internal __git_ps1"
  source $BASH_PATH/completion.d/git/git-prompt.sh
elif [[ ! -z $TMUX_STATUS_RIGHT_GIT_INTERNAL_PS1 ]]; then
  if [[ ! -e $TMUX_STATUS_RIGHT_GIT_INTERNAL_PS1 ]]; then
    for _fi in $(declare -F | command grep "__git_ps1") __git_eread __git_sequencer_status; do
      type $_fi 2>/dev/null | sed 1d >>$TMUX_STATUS_RIGHT_GIT_INTERNAL_PS1
    done
    unset _fi
  fi
fi
# }}}
# Less # {{{
if [[ -z $LESSOPEN ]]; then
  : ${LESSPIPE_PATH:="/usr/bin/lesspipe"}
  if [[ -x "$LESSPIPE_PATH" ]]; then
    eval "$(SHELL=/bin/sh $LESSPIPE_PATH)"
  fi
  if is-installed -w dpkg >/dev/null 2>&1 && dpkg -L libsource-highlight-common >/dev/null 2>&1; then
    export LESSOPEN="| $(dpkg -L libsource-highlight-common | command grep lesspipe) %s"
  fi
fi
export PAGER=less
export LESSCHARSET='utf-8'
# Use this if lesspipe.sh exists
export LESS="-diJRSwX -x4 -z-4 -+F -~"
# Less man page colors (makes Man pages more readable) # {{{
export LESS_TERMCAP_mb="$CGreen"
export LESS_TERMCAP_md="$CCyan"
export LESS_TERMCAP_me="$COff"
export LESS_TERMCAP_so="$CRed"
export LESS_TERMCAP_se="$COff"
export LESS_TERMCAP_us="$CGold"
export LESS_TERMCAP_ue="$COff"
# }}}
# }}}
# PS1 # {{{
if ${SET_TITLE_USE_SIMPLE_MODE:-true}; then
  export PROMPT_COMMAND="set-title-pane"
else
  export PROMPT_COMMAND="set-title --set-terminal --tmux-session"
fi
export PROMPT_COMMAND+="; bash_phistory; history -a"
export PROMPT_DIRTRIM=3

${SET_TITLE_WINDOW_TITLE:-false} && [[ -n $STY || -n $TMUX ]] && export PROMPT_COMMAND="set-title; $PROMPT_COMMAND"
${PS1_CHECK_ENV:-false} && export PROMPT_COMMAND+="; PS1_envUpdater"

export PS1_MODES=(usuper_full:usf super_full:sf default:d default_ssh:dshh short:s short_git:sg short_git_ssh:sgssh very_short:vs)

if [[ ! -z $EPOCHREALTIME ]]; then
  export PS0='\[${PWD:$((PS0_time=${EPOCHREALTIME/[,.]}, 0)):0}\]'
fi
PS1_STATUS=
if $IS_VSCODE; then # {{{
  export PS1_CFG_ADD_GIT=true
  export PS1_CFG_ADD_SEPARATOR=false
  export PS1_CFG_ADD_SPLIT=false
  export PS1_SSH_CHANGE=false # }}}
elif $IS_DOCKER; then # {{{
  [[ -z $TMUX ]] && export PS1_STATUS="short_git_ssh:default"
  [[ -z $PS1_HOSTNAME ]] && export PS1_HOSTNAME=${HOSTNAME:0:3} # }}}
elif [[ " $PERS_USERS " != *\ $USER\ * && $USER != 'root' ]]; then # {{{
  export PS1_STATUS="usuper_full:short_git"
fi # }}}
if [[ -n "$SSH_CLIENT" && ! -n $TMUX ]]; then
  ${PS1_SSH_CHANGE:-true} && export PS1_STATUS="short_git_ssh:default_ssh"
fi
[[ -z $PS1_STATUS ]] && export PS1_STATUS="short_git:default"
# }}}
# CapsLock <-> Ctrl # {{{
if false && ! $IS_MAC && [[ -n $DISPLAY ]]; then
  is-installed -w setxkbmap >/dev/null 2>&1 && setxkbmap -option 'caps:ctrl_modifier'
  if is-installed -w xcape >/dev/null 2>&1; then
    killall xcape >/dev/null 2>&1
    xcape -e "${CAPS_KEY:-Caps_Lock}=Escape"
  fi
fi
# }}}
# Disable stopping terminal by C-S # {{{
if type stty >/dev/null 2>&1; then
  stty -ixon 2>/dev/null
fi # }}}
# Source profiles' configurations # {{{
for profi in $BASH_PROFILES_FULL; do
  [[ -e $profi/cfg ]] && source $profi/cfg
done
export CD_LAST_DIRS_STORED="${CD_LAST_DIRS_STORED:1}"
# }}}
# Setup PROMPT_COMMAND # {{{
export PROMPT_COMMAND="PS1_env --save; PS1_setter; $PROMPT_COMMAND; PS1_env --restore"
# rid of systemd osc
export PROMPT_COMMAND_ORIG="${PROMPT_COMMAND[0]}"
unset PROMPT_COMMAND
export PROMPT_COMMAND="$PROMPT_COMMAND_ORIG"
# }}}
