#!/usr/bin/env bash
# vim: fdl=0

# Is installed # {{{
if ${RCSTUFF_COMPLETION_INSTALLED:-false}; then
  [[ $1 == '--force' ]] || ${RCSTUFF_FORCE:-false} || return 0
fi
BASHRC_COMPLETION_FULL=true
[[ $1 == '--force' ]] && shift
${RCSTUFF_FORCE:-false} && BASHRC_COMPLETION_FULL=true
export RCSTUFF_COMPLETION_INSTALLED=true
# }}}
if $BASHRC_COMPLETION_FULL; then # {{{
  _completion_vim() { # {{{
    COMPREPLY=()
    local cmd=${COMP_WORDS[0]}
    [[ "$(which $cmd)" != $BIN_PATH/vims/* ]] && return
    compl-old
  } # }}}
  _do_vim_completion() { # {{{
    local i=
    for i in {,_}{,g,m,r}{vi,view,vim,vimdiff}; do
      if [[ -e $BIN_PATH/vims/$i ]]; then
        while complete -r $i >/dev/null 2>&1; do :; done
        complete $COMPLETE_DEFAULT_PARAMS -F _completion_vim $i
      fi
    done
    complete $COMPLETE_DEFAULT_PARAMS -F _completion_vim vim-session
  }
  # }}}
  # Completion for git aliases defined in bin/git/extra-completion.sh # {{{
  for ii in $($SCRIPT_PATH/bin/git/extra-completion.sh --list); do
    eval "_git_${ii}() { compl-new; }"
  done
  for ii in $(cd $SCRIPT_PATH/bin/git; ls git-* 2>/dev/null); do
    f=${ii#git-} && f=${f//[-]/_}
    grep -q "@@" $SCRIPT_PATH/bin/git/$ii || continue
    eval "_git_$f() { compl-new; }"
  done
  # }}}
  # Set generic completion # {{{
  COMPLETION_GENERIC_UTILS_OLD+=" gitst"
  for ii in $COMPLETION_GENERIC_UTILS_OLD; do # {{{
    which $ii >/dev/null 2>&1 && compl-add --old $ii # || echoe -s "Util [$ii] not found"
  done # }}}
  for ii in $COMPLETION_GENERIC_UTILS; do # {{{
    which $ii >/dev/null 2>&1 && compl-add --new $ii # || echoe -s "Util [$ii] not found"
  done # }}}
  for ii in $(echo "$COMPLETION_GENERIC_FUNCTIONS" | tr ' ' '\n' | sort -u | tr '\n' ' '); do # {{{
    if type $ii >/dev/null 2>&1; then
      compl-add --new $ii
    else
      echoe -s "Function [$ii] not found"
    fi
  done # }}}
  for ii in $(echo "$COMPLETION_GENERIC_FUNCTIONS_OLD" | tr ' ' '\n' | sort -u | tr '\n' ' '); do # {{{
    if type $ii >/dev/null 2>&1; then
      compl-add --old $ii
    else
      echoe -s "Function [$ii] not found"
    fi
  done # }}}
  unset COMPLETION_GENERIC_UTILS COMPLETION_GENERIC_FUNCTIONS COMPLETION_GENERIC_UTILSCOMPLETION_GENERIC_FUNCTIONS_OLD
  # }}}
  # Hosts # {{{
  if [[ -e $HOME/.ssh/known_hosts ]] && tail -1 $HOME/.ssh/known_hosts | command grep -vq "^|1|"; then
    complete -W "$(cut -f 1 -d ' ' $HOME/.ssh/known_hosts | sed -e s/,.*//g | uniq | command grep -v "\[")" ssh
  fi # }}}
  # Vim # {{{
  _do_vim_completion
  unset _do_vim_completion
  # }}}
  # Oth # {{{
  complete | command grep -q " cdd$" || complete $COMPLETE_DEFAULT_PARAMS -W "$(cd_wrapper -- @@ - -i | tr '\n' ' ')" cdd
  declare -F _filedir >/dev/null && eval "$(type -a _filedir | tail -n +2 | sed 's/compopt -o filenames 2>/compopt -o filenames -o noquote 2>/')"
  compl-add --smart ./build.sh
  # }}}
  # tldr # {{{
  if [[ -e $HOME/.local/share/tldr ]]; then
    complete -W "$(q=($HOME/.local/share/tldr/*/*); sed 's@\.md @ @g' <<<${q[@]##*/})" tldr
  fi # }}}
  # all from own bins/ # {{{
  add_for_all() { # {{{
    local a_dir=$1 a_file=
    [[ -e $a_dir ]] || return
    for a_file in $a_dir/*; do
      [[ -e $a_file ]] || continue
      a_file="$(realpath "$a_file")"
      [[ -f $a_file && -x $a_file ]] || continue
      case $a_file in
      $RUNTIME_PATH/bin/* | $SCRIPT_PATH/*);;
      $BIN_PATH/*.sh);;
      *) continue
      esac
      [[ $(file -b "$a_file") =~ "ASCII text" ]] || continue
      compl-add $a_file
    done
  } # }}}
  add_for_all $SCRIPT_PATH/bin
  for pp in $BASH_PROFILES_FULL; do
    add_for_all $pp/bin
  done
  unset pp
  add_for_all $BIN_PATH
  add_for_all $RUNTIME_PATH/bin
  unset -f add_for_all
  # }}}
fi # }}}
# Source additional completions # {{{
if [[ -e $BASH_PATH/completion.d ]]; then
  for ii in $(ls $BASH_PATH/completion.d); do
    [[ -f $BASH_PATH/completion.d/$ii ]] && source $BASH_PATH/completion.d/$ii
  done
fi
if [[ -e $RUNTIME_PATH/completion.d ]]; then
  for ii in $(ls $RUNTIME_PATH/completion.d); do
    [[ -f $RUNTIME_PATH/completion.d/$ii && ( -x $RUNTIME_PATH/completion.d/$ii || $ii == *.sh || $ii == *.bash ) ]] && source $RUNTIME_PATH/completion.d/$ii
  done
fi
# }}}
# Source profile specic completions # {{{
for profi in $BASH_PROFILES_FULL; do
  [[ -e $profi/completion ]] && source $profi/completion
done
unset profi ii
# }}}
source $SCRIPT_PATH/bash/completion.alias
if [[ -e $COMPLETION_BASH_PATH/bash_completion ]]; then # {{{
  source $COMPLETION_BASH_PATH/bash_completion
  if ${BASHRC_GIT_COMPLETION_FIX:-true}; then
    [[ -e "$COMPLETION_BASH_PATH/completions/git" ]] && source "$COMPLETION_BASH_PATH/completions/git"
  fi
fi # }}}
# overrides of commons utils # {{{
_completion_npm() { # {{{
  COMPREPLY=( "" )
  [[ -e package.json ]] || return
  declare -xa opts
  if (( $COMP_CWORD > 1 )); then
    case ${COMP_WORDS[COMP_CWORD - 1]} in
    run) opts=( $(jq -r '.scripts | keys[]' package.json 2>/dev/null) );;
    exec) opts=( $(jq -r '.devDependencies | keys[] | select(startswith("@") | not)' package.json 2>/dev/null) )
    esac
  fi
  compl-static
} # }}}
_completion_npx() { # {{{
  COMPREPLY=( "" )
  [[ -e package.json ]] || return
  declare -xa opts
  if (( $COMP_CWORD == 1 )); then
    opts=( $(jq -r '.devDependencies | keys[] | select(startswith("@") | not)' package.json 2>/dev/null) )
  fi
  compl-static
} # }}}
complete $COMPLETE_DEFAULT_PARAMS -F _completion_npm npm
complete $COMPLETE_DEFAULT_PARAMS -F _completion_npx npx
compl-add --old cd
# }}}
true
