#!/bin/bash

# Is installed # {{{
${RCSTUFF_CYGWIN_INSTALLED:-false} && [[ $1 != '--force' ]] && return 0
export RCSTUFF_CYGWIN_INSTALLED=true
[[ $1 == '--force' ]] && shift
# }}}
# Env {{{
# PS1='\w $(__git_ps1 "(%s)")\$ '
export find_cmd=/bin/find
export PATH=/bin:$PATH
export LANG=en_US.UTF-8
# }}}
for i in $BASH_PROFILES; do # {{{
  [[ -e $BASH_PATH/profiles/$i/cygwin ]] && source $BASH_PATH/profiles/$i/cygwin
done # }}}

