#!/usr/bin/env bash
# vim: fdl=0

if [ "$TERM" != 'dumb' ]; then
  if [ -f "$HOME/.bashrc" ]; then
   source $HOME/.bashrc --do-min
  fi
fi

export PATH="$HOME/.cargo/bin:$PATH"
export QT_QPA_PLATFORMTHEME="qt5ct"

