#!/usr/bin/env bash
# vim: fdl=0

# Is installed # {{{
${RCSTUFF_RUNTIME_POST_INSTALLED:-false} && [[ $1 != '--force' ]] && return 0
[[ $1 == '--force' ]] && shift
export RCSTUFF_RUNTIME_POST_INSTALLED=true
# }}}
# Runtime file # {{{
RUNTIME_POST_FILE=$RUNTIME_PATH/runtime-post.bash
for rpost in $($BASH_PATH/env-ext.sh get-plugins runtime-post.bash); do
  source $rpost
done
unset RUNTIME_POST_FILE rpost
# }}}
# TMUX_STATUS_RIGHT_EXTRA # {{{
if [[ -z $TMUX_STATUS_RIGHT_EXTRA_SORTED ]]; then
  TMUX_STATUS_RIGHT_EXTRA_SORTED=
  ( ${TMUX_STATUS_RIGHT_EXTRA_HAS_BATTERY:-false} || [[ -n $TMUX_SB_BATTERY_THRESHOLDS ]] ) && TMUX_STATUS_RIGHT_EXTRA+=" 016:battery"
  while read l; do
    l=$(echo ${l#*:})
    [[ -z $l ]] && continue
    export TMUX_STATUS_RIGHT_EXTRA_SORTED+="$l "
  done < <(echo -e "$TMUX_STATUS_RIGHT_EXTRA" | tr ' ' '\n' | command grep -v '^#' | sort -ut ':' -k2,2 | sort -nt ':' -k1,1)
  unset l TMUX_STATUS_RIGHT_EXTRA
fi # }}}
if ! is-installed --no-cache -t kp-pp; then # {{{
  source "$SCRIPT_PATH/inits/keep-pass/keep-pass-env.sh"
fi # }}}
# Check personalities # {{{
[[ -z $PERS_USERS ]] && echoe "Personalities not found!!!" && sleep 2
# }}}
# nvm # {{{
if [[ -e $HOME/.nvm ]] && ${NODE_USE_NVM:-false}; then
  export NVM_DIR="$HOME/.nvm"
  [[ -s $NVM_DIR/nvm.sh ]] && source $NVM_DIR/nvm.sh
  [[ -s $NVM_DIR/bash_completion ]] && source $NVM_DIR/bash_completion
fi # }}}
# Unicode extra chars # {{{
if [[ ! -z "$UNICODE_EXTRA_CHARS_FILE" && ! -e "$UNICODE_EXTRA_CHARS_FILE" ]]; then
  touch "$UNICODE_EXTRA_CHARS_FILE"
  {
    echo "declare -Ag UNICODE_EXTRA_CHARS"
    for i in $(echo ${!UNICODE_EXTRA_CHARS[*]} | tr ' ' '\n' | sort); do
      echo "UNICODE_EXTRA_CHARS[$i]=\"${UNICODE_EXTRA_CHARS[$i]}\""
    done
  } >"$UNICODE_EXTRA_CHARS_FILE"
  unset i
fi # }}}
# fzf override # {{{
if $FZF_INSTALLED && [[ -n $PS1 ]]; then # {{{
  eval "$(fzf --bash)"
  __fzf_handler_git() { # {{{
    mode=$1; shift
    case $mode in
    init) # {{{
      p="$PWD"; origPath="$PWD"
      prompt="> "
      expectList="";; # }}}
    loop) # {{{
      ;; # }}}
    expect) # {{{
      local key=$1
      case $key in
      esac;; # }}}
    result) # {{{
      cat - | while read -r item; do
        [[ "$item" =~ .*\|([0-9a-f]{5,})\|.* ]] || continue
        printf "%s\n" "${BASH_REMATCH[1]}"
      done;; # }}}
    preview) # {{{
      local line="$1"
      [[ "$line" =~ .*\|([0-9a-f]{5,})\|.* ]] || return
      local sha=${BASH_REMATCH[1]}
      git log --pretty=fuller --date=local -1 "$sha"
      echo; echo '    ----'
      git diff $sha~..$sha --name-status | sed -e 's/^/    /'
      echo '    ----'; echo
      git diff -w $sha~..$sha \
      | if which colordiff >/dev/null 2>&1; then colordiff -u; else cat -; fi;; # }}}
    esac
  } # }}}
  __fzf_handler_fs() { # {{{
    local mode=$1; shift
    local key_upper="ctrl-u" key_home="ctrl-h" key_into="ctrl-e" key_orig="ctrl-o"
    case $mode in
    init) # {{{
      p="$PWD"; origPath="$PWD"
      expectList="--expect $key_upper --expect $key_home --expect $key_into --expect $key_orig";; # }}}
    loop) # {{{
      command cd "$p"
      prompt="> "
      [[ $PWD != $origPath ]] && prompt="${PWD/$HOME/\~}> ";; # }}}
    expect) # {{{
      local key=$1
      case $key in
      $key_upper) p="$(cd ..; pwd)";;
      $key_home)  p="$HOME";;
      $key_orig)  p="$origPath";;
      $key_into)
        p="$(echo "$list" | sed -n '2p')"
        $dirMode || p="$(dirname "$p")"
        p="$PWD/$p";;
      esac;; # }}}
    result) # {{{
      cat - | while read -r item; do
        printf '%q\n' "$PWD/$item"
      done \
      | sed -e 's|'"$PWD/"'||';; # }}}
    preview) # {{{
      local f="$1"
      [[ -e $f || ( -h $f && -f $(readlink -f $f) ) ]] || return
      cat.sh -p $f;; # }}}
    esac
  } # }}}
  __fzf_select__() { # {{{
    local dirMode=false
    FZF_DEFAULT_COMMAND="${FZF_CTRL_T_COMMAND:-} | sed 's|^\./||'"
    local optsDef="--reverse ${FZF_CTRL_T_OPTS-}" opts="-m --ansi" optsWalker="--walker=file,dir,follow,hidden --scheme=path"
    local handler="__fzf_handler_fs"
    while [[ ! -z $1 ]]; do # {{{
      case $1 in
      --cmd) # {{{
        FZF_DEFAULT_COMMAND="$2"; shift
        handler="";; # }}}
      --dir) # {{{
        dirMode=true
        optsWalker="--walker=dir,follow,hidden --scheme=path"
        FZF_DEFAULT_COMMAND="${FZF_ALT_C_COMMAND:-} | sed 's|^\./||'"
        optsDef="${FZF_ALT_C_OPTS-}";; # }}}
      --opts-walker) # {{{
        optsWalker="$2"; shift;; # }}}
      --opts) # {{{
        opts="$s"; shift;; # }}}
      --handler) # {{{
        handler="$2"; shift;; # }}}
      *) break;;
      esac; shift
    done # }}}
    FZF_DEFAULT_OPTS=$(__fzf_defaults "$optsWalker" "$optsDef $opts")
    (
      export -f $handler
      expectList= prompt=
      $handler init
      fzfCmd="$(__fzfcmd)"
      while true; do
        $handler loop
        list="$(FZF_DEFAULT_OPTS_FILE='' $fzfCmd "$@" --prompt "$prompt" --preview "$handler preview {}" $expectList)"
        if [[ -n $expectList ]]; then
          local expectKey=$(echo "$list" | sed -n '1p')
          if [[ -n $expectKey ]]; then
            $handler expect $expectKey
            continue
          fi
          list="$(echo "$list" | sed '1d')"
        fi
        [[ -n $list ]] && echo "$list"
        break
      done
    ) | $handler result | tr '\n' ' '
  } # }}}
  __fzf-file-widget() { # {{{
    local selected="$(__fzf_select__ "$@")"
    [[ -n $selected ]] || return 0
    READLINE_LINE="${READLINE_LINE:0:$READLINE_POINT}$selected${READLINE_LINE:$READLINE_POINT}"
    READLINE_POINT=$(( READLINE_POINT + ${#selected} ))
  } # }}}
  __fzf-dir-widget() { # {{{
    local selected="$(__fzf_select__ --dir "$@")"
    [[ -n $selected ]] || return 0
    READLINE_LINE="${READLINE_LINE:0:$READLINE_POINT}$selected${READLINE_LINE:$READLINE_POINT}"
    READLINE_POINT=$(( READLINE_POINT + ${#selected} ))
  } # }}}
  __fzf-cd-widget() { # {{{
    __fzf-dir-widget "$@"
  } # }}}
  __fzf-git-widget() { # {{{
    local selected="$(__fzf_select__ --cmd "git log --graph --oneline --decorate --color --format='%C(240)|%C(172)%h%C(240)|%C(reset)%C(auto)%d %C(dim white)%s%C(reset)' --exclude=refs/remotes/* --exclude=refs/tags/* --decorate-refs-exclude=refs/tags/tmp/sync/* --branches --remotes" --handler "__fzf_handler_git")"
    [[ -n $selected ]] || return 0
    READLINE_LINE="${READLINE_LINE:0:$READLINE_POINT}$selected${READLINE_LINE:$READLINE_POINT}"
    READLINE_POINT=$(( READLINE_POINT + ${#selected} ))
  } # }}}
  __fzf-history() { # {{{
    local rlPoint=$READLINE_POINT
    READLINE_POINT=
    READLINE_LINE="$( history -r; __fzf_history__)"
    READLINE_POINT=$rlPoint
  } # }}}
  __fzf-env-widget() { # {{{
    declare -a resA
    readarray -t resA < <(\
      compgen -v | grep "^[A-Z]" \
      | fzf +m --sort \
          --prompt 'env> ' \
          --preview 'eval echo \${1}' --preview-window 'nohidden' \
          --expect ctrl-n \
          --expect ctrl-q \
          --expect ctrl-v)
    (( $? == 0 )) || return 1
    local key="${resA[0]}" selected="${resA[1]}"
    [[ -n $selected ]] || return 1
    case $key in
    '') selected="\$$selected";;
    ctrl-n) ;;
    ctrl-q) local -n ref="$selected"; selected="\"$ref\"";;
    ctrl-v) local -n ref="$selected"; selected="$ref";;
    esac
    READLINE_LINE="${READLINE_LINE:0:$READLINE_POINT}$selected${READLINE_LINE:$READLINE_POINT}"
    READLINE_POINT=$((READLINE_POINT + ${#selected}))
  } # }}}
  bind -m vi-command -r "\C-r"
  bind -m vi-insert  -r "\C-r"
  bind -m vi-command -x '"\C-w\C-e": "__fzf-env-widget"'
  bind -m vi-insert  -x '"\C-w\C-e": "__fzf-env-widget"'
  bind -m vi-command -x '"\C-w\C-g": "__fzf-git-widget"'
  bind -m vi-insert  -x '"\C-w\C-g": "__fzf-git-widget"'
  bind -m vi-command -x '"\C-w\C-r": "__fzf-history"'
  bind -m vi-insert  -x '"\C-w\C-r": "__fzf-history"'
  bind -m vi-command -x '"\C-r": "__fzf-history"'
  bind -m vi-insert  -x '"\C-r": "__fzf-history"'
  bind -m vi-command -x '"\C-t": "__fzf-file-widget"'
  bind -m vi-insert  -x '"\C-t": "__fzf-file-widget"'
  bind -m vi-insert     '"\ec": "\C-gcd\C-m"'
  bind -m vi-command -x '"\ed": "__fzf-cd-widget"'
  bind -m vi-insert  -x '"\ed": "__fzf-cd-widget"'
fi # }}}
# }}}
if ${TMUX_POPUP:-false}; then # {{{
  if ! $TMUX_POPUP_SILENT; then
    echoe -m popup "s=[$s]"
    echoe -m popup "d=[$d]"
  fi
  export BASH_PHISTORY_FILE=
  export TMUX_SESSION=POPUP
  if [[ ! -z $d ]]; then
    set-utils -h "$d" +basic +hist +remember-conf-dir=.remb +note-file=notes.txt
  fi
fi # }}}
if $IS_DOCKER; then # {{{
  if ! $IS_VSCODE && $BASHRC_FULL_START; then # {{{
    $ENV_SCRIPTS/docker-tools/clipboard-docker.sh &
    disown $!
  fi # }}}
fi # }}}
if $IS_VSCODE; then # {{{
  set-utils -h "$APPS_CFG_PATH/vscode" +basic +hist +remember-conf-dir=.remb +note-file=notes.txt
fi # }}}
unset -f set-utils

